sync-symphony:
    #!/usr/bin/env bash
    set -euo pipefail
    submodule_path="vendor/openai-symphony"
    spec_path="${submodule_path}/SPEC.md"
    if [[ ! -e "${submodule_path}/.git" ]]; then
      echo "missing ${submodule_path}; run: git submodule update --init ${submodule_path}" >&2
      exit 1
    fi
    git submodule update --remote vendor/openai-symphony
    if [[ ! -f "${spec_path}" ]]; then
      echo "missing ${spec_path}" >&2
      exit 1
    fi
    submodule_commit="$(git -C "${submodule_path}" rev-parse HEAD)"
    if command -v sha256sum >/dev/null 2>&1; then
      spec_sha256="$(sha256sum "${spec_path}" | cut -d ' ' -f 1)"
    else
      spec_sha256="$(shasum -a 256 "${spec_path}" | cut -d ' ' -f 1)"
    fi
    cat > .symphony-spec.lock <<LOCK
    # Generated by just sync-symphony.
    submodule_path=vendor/openai-symphony
    submodule_url=https://github.com/openai/symphony
    submodule_branch=main
    submodule_commit=${submodule_commit}
    spec_path=vendor/openai-symphony/SPEC.md
    spec_sha256=${spec_sha256}
    LOCK
    bun run scripts/gen-conformance-trace.ts --write
