export const TRPC_RESOURCES = {
  agentRuns: "agent_runs",
  agents: "agents",
  artifacts: "artifacts",
  audit: "audit",
  auth: "auth",
  backup: "backup",
  connectors: "connectors",
  context: "context",
  customFields: "custom_fields",
  docComments: "doc_comments",
  docLinks: "doc_links",
  docVersions: "doc_versions",
  doctor: "doctor",
  docs: "docs",
  errorLogs: "error_logs",
  flags: "flags",
  fulcrumSkills: "fulcrum_skills",
  inference: "inference",
  invitations: "invitations",
  memory: "memory",
  notifications: "notifications",
  orchestration: "orchestration",
  orgs: "orgs",
  projects: "projects",
  reports: "reports",
  repoBranches: "repo_branches",
  repoCommits: "repo_commits",
  repos: "repos",
  routing: "routing",
  runs: "runs",
  savedViews: "saved_views",
  search: "search",
  sprints: "sprints",
  tasks: "tasks",
  telemetry: "telemetry",
  theme: "theme",
  webhooks: "webhooks",
} as const;

export const TRPC_ACTIONS = {
  archive: "archive",
  assemble: "assemble",
  bulkDelete: "bulkDelete",
  bulkUpdate: "bulkUpdate",
  cancel: "cancel",
  cancelRun: "cancelRun",
  classify: "classify",
  clear: "clear",
  close: "close",
  config: "config",
  create: "create",
  delete: "delete",
  disable: "disable",
  download: "download",
  dryRun: "dryRun",
  embed: "embed",
  enable: "enable",
  evaluate: "evaluate",
  export: "export",
  get: "get",
  getLogs: "getLogs",
  getTheme: "getTheme",
  health: "health",
  install: "install",
  list: "list",
  listThemes: "listThemes",
  markAllRead: "markAllRead",
  markRead: "markRead",
  metrics: "metrics",
  mute: "mute",
  optIn: "optIn",
  optOut: "optOut",
  preview: "preview",
  preflight: "preflight",
  pull: "pull",
  purge: "purge",
  query: "query",
  register: "register",
  remove: "remove",
  renderPromptPreview: "renderPromptPreview",
  resolve: "resolve",
  resolveConflict: "resolveConflict",
  restore: "restore",
  retry: "retry",
  retryRun: "retryRun",
  revoke: "revoke",
  rm: "rm",
  run: "run",
  search: "search",
  set: "set",
  setDependencies: "setDependencies",
  setOverride: "setOverride",
  setParent: "setParent",
  setRollout: "setRollout",
  setTheme: "setTheme",
  start: "start",
  status: "status",
  suggest: "suggest",
  sync: "sync",
  test: "test",
  testProfile: "testProfile",
  tokenize: "tokenize",
  unarchive: "unarchive",
  unregister: "unregister",
  unmute: "unmute",
  uninstall: "uninstall",
  update: "update",
  updateRole: "updateRole",
  upgrade: "upgrade",
  upload: "upload",
  whoami: "whoami",
} as const;

export type TrpcPermission = {
  resource: string;
  action: string;
};

export type TrpcProcedureMeta = {
  permission?: TrpcPermission;
};

export const LOCAL_DEV_PERMISSION_BYPASS_FLAG = "trpc-permission-local-dev-bypass";

export function permission(resource: string, action: string): TrpcProcedureMeta {
  return { permission: { resource, action } };
}
