// Pre-existing per-route ApiOperation/response decorator residuals.
// Tracked separately; new routes MUST carry their own decorators.
// Generated 2026-05-19 from the gate's initial sweep.
export const API_DECORATOR_RESIDUALS = [
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::abortSession missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::abortSession missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::connectBridge missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::connectBridge missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::deleteSavedSession missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::deleteSavedSession missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::forkFromCheckpoint missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::forkFromCheckpoint missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::pauseSession missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::pauseSession missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::reconnectSession missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::reconnectSession missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::restoreCheckpoint missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::restoreCheckpoint missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::resumeSavedSession missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::resumeSavedSession missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::resumeSession missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-profile-public-api.controller.ts: AgentProfilePublicApiController::resumeSession missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicApiController::listCandidateIssues missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicApiController::listCandidateIssues missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicApiController::listRunIssuesByStates missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicApiController::listRunIssuesByStates missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicApiController::loadRun missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicApiController::loadRun missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicApiController::loadStatus missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicApiController::loadStatus missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicApiController::refreshRuns missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicApiController::refreshRuns missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunPagesController::archiveArtifact missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunPagesController::archiveArtifact missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunPagesController::dispatchPromptRun missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunPagesController::dispatchPromptRun missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunPagesController::linkArtifactToDoc missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunPagesController::linkArtifactToDoc missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunPagesController::listProjectRunRows missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunPagesController::listProjectRunRows missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunPagesController::loadRunPage missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunPagesController::loadRunPage missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunPagesController::loadRunsPage missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunPagesController::loadRunsPage missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunPagesController::promoteArtifactToMemory missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunPagesController::promoteArtifactToMemory missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunPagesController::recordApprovalDecision missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunPagesController::recordApprovalDecision missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunsController::cancelRun missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunsController::cancelRun missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunsController::dispatchRun missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunsController::dispatchRun missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunsController::listRuns missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunsController::listRuns missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunsController::loadRun missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunsController::loadRun missing per-route response decorator",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunsController::retryRun missing ApiOperation",
  "services/execution-orchestration/src/interface/http/agent-run-public-api.controller.ts: AgentRunPublicRunsController::retryRun missing per-route response decorator",
  "services/feature-flags/src/interface/http/controllers/feature-experiment-public-api.controller.ts: FeatureExperimentPublicApiController::assign missing ApiOperation",
  "services/feature-flags/src/interface/http/controllers/feature-experiment-public-api.controller.ts: FeatureExperimentPublicApiController::assign missing per-route response decorator",
  "services/feature-flags/src/interface/http/controllers/feature-experiment-public-api.controller.ts: FeatureExperimentPublicApiController::assignments missing ApiOperation",
  "services/feature-flags/src/interface/http/controllers/feature-experiment-public-api.controller.ts: FeatureExperimentPublicApiController::assignments missing per-route response decorator",
  "services/feature-flags/src/interface/http/controllers/feature-experiment-public-api.controller.ts: FeatureExperimentPublicApiController::create missing ApiOperation",
  "services/feature-flags/src/interface/http/controllers/feature-experiment-public-api.controller.ts: FeatureExperimentPublicApiController::create missing per-route response decorator",
  "services/feature-flags/src/interface/http/controllers/feature-experiment-public-api.controller.ts: FeatureExperimentPublicApiController::list missing ApiOperation",
  "services/feature-flags/src/interface/http/controllers/feature-experiment-public-api.controller.ts: FeatureExperimentPublicApiController::list missing per-route response decorator",
  "services/feature-flags/src/interface/http/controllers/feature-experiment-public-api.controller.ts: FeatureExperimentPublicApiController::metrics missing ApiOperation",
  "services/feature-flags/src/interface/http/controllers/feature-experiment-public-api.controller.ts: FeatureExperimentPublicApiController::metrics missing per-route response decorator",
  "services/feature-flags/src/interface/http/controllers/feature-experiment-public-api.controller.ts: FeatureExperimentPublicApiController::recordConversion missing ApiOperation",
  "services/feature-flags/src/interface/http/controllers/feature-experiment-public-api.controller.ts: FeatureExperimentPublicApiController::recordConversion missing per-route response decorator",
  "services/integration-hub/src/interface/http/connector-public-api.controller.ts: ConnectorRunPublicApiController::getRun missing ApiOperation",
  "services/integration-hub/src/interface/http/connector-public-api.controller.ts: ConnectorRunPublicApiController::getRun missing per-route response decorator",
  "services/integration-hub/src/interface/http/connector-public-api.controller.ts: ConnectorRunPublicApiController::listRuns missing ApiOperation",
  "services/integration-hub/src/interface/http/connector-public-api.controller.ts: ConnectorRunPublicApiController::listRuns missing per-route response decorator",
  "services/integration-hub/src/interface/http/connector-public-api.controller.ts: ProjectConnectorPublicApiController::list missing ApiOperation",
  "services/integration-hub/src/interface/http/connector-public-api.controller.ts: ProjectConnectorPublicApiController::list missing per-route response decorator",
  "services/integration-hub/src/interface/http/connector-public-api.controller.ts: ProjectConnectorPublicApiController::upsert missing ApiOperation",
  "services/integration-hub/src/interface/http/connector-public-api.controller.ts: ProjectConnectorPublicApiController::upsert missing per-route response decorator",
  "services/integration-hub/src/interface/http/connector-public-api.controller.ts: ProjectConnectorSyncPublicApiController::sync missing ApiOperation",
  "services/integration-hub/src/interface/http/connector-public-api.controller.ts: ProjectConnectorSyncPublicApiController::sync missing per-route response decorator",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: ProjectRepositoryPublicApiController::add missing ApiOperation",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: ProjectRepositoryPublicApiController::add missing per-route response decorator",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: ProjectRepositoryPublicApiController::link missing ApiOperation",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: ProjectRepositoryPublicApiController::link missing per-route response decorator",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: ProjectRepositoryPublicApiController::list missing ApiOperation",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: ProjectRepositoryPublicApiController::list missing per-route response decorator",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryBranchPublicApiController::getBranch missing ApiOperation",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryBranchPublicApiController::getBranch missing per-route response decorator",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryBranchPublicApiController::listBranches missing ApiOperation",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryBranchPublicApiController::listBranches missing per-route response decorator",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryCommitPublicApiController::getCommit missing ApiOperation",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryCommitPublicApiController::getCommit missing per-route response decorator",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryCommitPublicApiController::listCommits missing ApiOperation",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryCommitPublicApiController::listCommits missing per-route response decorator",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::getRepositoryFile missing ApiOperation",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::getRepositoryFile missing per-route response decorator",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::getRepositoryStatus missing ApiOperation",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::getRepositoryStatus missing per-route response decorator",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::getRepositoryTree missing ApiOperation",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::getRepositoryTree missing per-route response decorator",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::listRepositories missing ApiOperation",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::listRepositories missing per-route response decorator",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::loadRepository missing ApiOperation",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::loadRepository missing per-route response decorator",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::registerRepository missing ApiOperation",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::registerRepository missing per-route response decorator",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::syncRepositories missing ApiOperation",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::syncRepositories missing per-route response decorator",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::syncRepository missing ApiOperation",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::syncRepository missing per-route response decorator",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::unregisterRepository missing ApiOperation",
  "services/integration-hub/src/interface/http/repository-public-api.controller.ts: RepositoryPublicApiController::unregisterRepository missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::createAttachment missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::createAttachment missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::createComment missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::createComment missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::createDocument missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::createDocument missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::createLink missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::createLink missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::deleteAttachment missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::deleteAttachment missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::deleteCollaborationState missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::deleteCollaborationState missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::deleteComment missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::deleteComment missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::deleteDocument missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::deleteDocument missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::deleteLink missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::deleteLink missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::diffVersionById missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::diffVersionById missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::diffVersions missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::diffVersions missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::getDocument missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::getDocument missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::getVersion missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::getVersion missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::getVersionById missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::getVersionById missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::listAttachments missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::listAttachments missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::listBacklinks missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::listBacklinks missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::listCollaborationStates missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::listCollaborationStates missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::listComments missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::listComments missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::listDocuments missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::listDocuments missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::listForwardLinks missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::listForwardLinks missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::listTemplates missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::listTemplates missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::listVersions missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::listVersions missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::patchCollaborationState missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::patchCollaborationState missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::patchComment missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::patchComment missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::patchDocument missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::patchDocument missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::resolveComment missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::resolveComment missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::resolveTemplate missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::resolveTemplate missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::restoreVersion missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::restoreVersion missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::restoreVersionById missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/document-public-api.controller.ts: DocumentPublicApiController::restoreVersionById missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/memory-public-api.controller.ts: ContextPreviewPublicApiController::previewContext missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/memory-public-api.controller.ts: MemoryPublicApiController::createMemory missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/memory-public-api.controller.ts: MemoryPublicApiController::createMemory missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/memory-public-api.controller.ts: MemoryPublicApiController::deleteMemory missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/memory-public-api.controller.ts: MemoryPublicApiController::listMemories missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/memory-public-api.controller.ts: MemoryPublicApiController::searchMemories missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/memory-public-api.controller.ts: MemoryPublicApiController::searchMemories missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/search-public-api.controller.ts: SearchPublicApiController::createSavedSearch missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/search-public-api.controller.ts: SearchPublicApiController::createSavedSearch missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/search-public-api.controller.ts: SearchPublicApiController::deleteSavedSearch missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/search-public-api.controller.ts: SearchPublicApiController::deleteSavedSearch missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/search-public-api.controller.ts: SearchPublicApiController::listSavedSearches missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/search-public-api.controller.ts: SearchPublicApiController::listSavedSearches missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/search-public-api.controller.ts: SearchPublicApiController::recordClick missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/search-public-api.controller.ts: SearchPublicApiController::recordClick missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/search-public-api.controller.ts: SearchPublicApiController::search missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/search-public-api.controller.ts: SearchPublicApiController::snapshot missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/search-public-api.controller.ts: SearchPublicApiController::snapshot missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/search-public-api.controller.ts: SearchPublicApiController::suggest missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/search-public-api.controller.ts: SearchPublicApiController::suggest missing per-route response decorator",
  "services/knowledge-workspace/src/interface/http/search-public-api.controller.ts: SearchPublicApiController::updateSavedSearch missing ApiOperation",
  "services/knowledge-workspace/src/interface/http/search-public-api.controller.ts: SearchPublicApiController::updateSavedSearch missing per-route response decorator",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::configureChannel missing ApiOperation",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::configureChannel missing per-route response decorator",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::createRule missing ApiOperation",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::createRule missing per-route response decorator",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::deleteRule missing per-route response decorator",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::getQuietHours missing ApiOperation",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::getQuietHours missing per-route response decorator",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::getRule missing per-route response decorator",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::getSettings missing ApiOperation",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::getSettings missing per-route response decorator",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::listMutes missing ApiOperation",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::listMutes missing per-route response decorator",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::listNotifications missing ApiOperation",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::listNotifications missing per-route response decorator",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::listRules missing ApiOperation",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::listRules missing per-route response decorator",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::markAllRead missing ApiOperation",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::markAllRead missing per-route response decorator",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::markRead missing ApiOperation",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::markRead missing per-route response decorator",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::mute missing ApiOperation",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::mute missing per-route response decorator",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::setQuietHours missing ApiOperation",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::setQuietHours missing per-route response decorator",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::testChannel missing ApiOperation",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::testChannel missing per-route response decorator",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::unmute missing ApiOperation",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::unmute missing per-route response decorator",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::unreadCount missing ApiOperation",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::unreadCount missing per-route response decorator",
  "services/notification-center/src/interface/http/notification-public-api.controller.ts: NotificationPublicApiController::updateRule missing per-route response decorator",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::classify missing ApiOperation",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::classify missing per-route response decorator",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::generate missing ApiOperation",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::generate missing per-route response decorator",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::getConfig missing ApiOperation",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::getConfig missing per-route response decorator",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::listBackends missing ApiOperation",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::listBackends missing per-route response decorator",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::listModels missing ApiOperation",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::listModels missing per-route response decorator",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::probeBackends missing ApiOperation",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::probeBackends missing per-route response decorator",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::pullModel missing ApiOperation",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::pullModel missing per-route response decorator",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::removeModel missing ApiOperation",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::removeModel missing per-route response decorator",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::setConfig missing ApiOperation",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::setConfig missing per-route response decorator",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::setProvider missing ApiOperation",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::setProvider missing per-route response decorator",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::testProvider missing ApiOperation",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::testProvider missing per-route response decorator",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::tokenize missing ApiOperation",
  "services/platform-core/src/interface/http/inference-public-api.controller.ts: InferencePublicApiController::tokenize missing per-route response decorator",
  "services/platform-core/src/interface/http/settings-public-api.controller.ts: SettingsPublicApiController::getSetting missing per-route response decorator",
  "services/platform-core/src/interface/http/settings-public-api.controller.ts: SettingsPublicApiController::listSettings missing ApiOperation",
  "services/platform-core/src/interface/http/settings-public-api.controller.ts: SettingsPublicApiController::listSettings missing per-route response decorator",
  "services/platform-core/src/interface/http/settings-public-api.controller.ts: SettingsPublicApiController::setSetting missing per-route response decorator",
  "services/platform-core/src/interface/http/theme-settings.controller.ts: ThemeSettingsApiController::getProfile missing ApiOperation",
  "services/platform-core/src/interface/http/theme-settings.controller.ts: ThemeSettingsApiController::getProfile missing per-route response decorator",
  "services/platform-core/src/interface/http/theme-settings.controller.ts: ThemeSettingsApiController::getToken missing per-route response decorator",
  "services/platform-core/src/interface/http/theme-settings.controller.ts: ThemeSettingsApiController::listTokens missing ApiOperation",
  "services/platform-core/src/interface/http/theme-settings.controller.ts: ThemeSettingsApiController::listTokens missing per-route response decorator",
  "services/platform-core/src/interface/http/theme-settings.controller.ts: ThemeSettingsApiController::setToken missing per-route response decorator",
  "services/platform-core/src/interface/http/theme-settings.controller.ts: ThemeSettingsApiController::updateProfile missing per-route response decorator",
  "services/work-management/src/interface/http/automation-public-api.controller.ts: AutomationPublicApiController::templates missing ApiOperation",
  "services/work-management/src/interface/http/automation-public-api.controller.ts: AutomationPublicApiController::templates missing per-route response decorator",
  "services/work-management/src/interface/http/planning-structure-public-api.controller.ts: PlanningStructurePublicApiController::addLabelTask missing ApiOperation",
  "services/work-management/src/interface/http/planning-structure-public-api.controller.ts: PlanningStructurePublicApiController::addLabelTask missing per-route response decorator",
  "services/work-management/src/interface/http/planning-structure-public-api.controller.ts: PlanningStructurePublicApiController::addModuleTask missing ApiOperation",
  "services/work-management/src/interface/http/planning-structure-public-api.controller.ts: PlanningStructurePublicApiController::createIntake missing ApiOperation",
  "services/work-management/src/interface/http/planning-structure-public-api.controller.ts: PlanningStructurePublicApiController::createLabel missing ApiOperation",
  "services/work-management/src/interface/http/planning-structure-public-api.controller.ts: PlanningStructurePublicApiController::deleteIntake missing ApiOperation",
  "services/work-management/src/interface/http/planning-structure-public-api.controller.ts: PlanningStructurePublicApiController::deleteIntake missing per-route response decorator",
  "services/work-management/src/interface/http/planning-structure-public-api.controller.ts: PlanningStructurePublicApiController::deleteLabel missing ApiOperation",
  "services/work-management/src/interface/http/planning-structure-public-api.controller.ts: PlanningStructurePublicApiController::deleteLabel missing per-route response decorator",
  "services/work-management/src/interface/http/planning-structure-public-api.controller.ts: PlanningStructurePublicApiController::deleteModule missing ApiOperation",
  "services/work-management/src/interface/http/planning-structure-public-api.controller.ts: PlanningStructurePublicApiController::removeLabelTask missing ApiOperation",
  "services/work-management/src/interface/http/planning-structure-public-api.controller.ts: PlanningStructurePublicApiController::removeLabelTask missing per-route response decorator",
  "services/work-management/src/interface/http/planning-structure-public-api.controller.ts: PlanningStructurePublicApiController::removeModuleTask missing ApiOperation",
  "services/work-management/src/interface/http/planning-structure-public-api.controller.ts: PlanningStructurePublicApiController::updateIntake missing ApiOperation",
  "services/work-management/src/interface/http/planning-structure-public-api.controller.ts: PlanningStructurePublicApiController::updateLabel missing ApiOperation",
  "services/work-management/src/interface/http/project-public-api.controller.ts: ProjectPublicApiController::createProject missing ApiOperation",
  "services/work-management/src/interface/http/project-public-api.controller.ts: ProjectPublicApiController::createProject missing per-route response decorator",
  "services/work-management/src/interface/http/project-public-api.controller.ts: ProjectPublicApiController::dashboard missing ApiOperation",
  "services/work-management/src/interface/http/project-public-api.controller.ts: ProjectPublicApiController::dashboard missing per-route response decorator",
  "services/work-management/src/interface/http/project-public-api.controller.ts: ProjectPublicApiController::deleteProject missing ApiOperation",
  "services/work-management/src/interface/http/project-public-api.controller.ts: ProjectPublicApiController::deleteProject missing per-route response decorator",
  "services/work-management/src/interface/http/project-public-api.controller.ts: ProjectPublicApiController::getProject missing ApiOperation",
  "services/work-management/src/interface/http/project-public-api.controller.ts: ProjectPublicApiController::getProject missing per-route response decorator",
  "services/work-management/src/interface/http/project-public-api.controller.ts: ProjectPublicApiController::listProjects missing ApiOperation",
  "services/work-management/src/interface/http/project-public-api.controller.ts: ProjectPublicApiController::listProjects missing per-route response decorator",
  "services/work-management/src/interface/http/project-public-api.controller.ts: ProjectPublicApiController::patchProject missing ApiOperation",
  "services/work-management/src/interface/http/project-public-api.controller.ts: ProjectPublicApiController::patchProject missing per-route response decorator",
  "services/work-management/src/interface/http/project-public-api.controller.ts: ProjectPublicApiController::projectStats missing ApiOperation",
  "services/work-management/src/interface/http/project-public-api.controller.ts: ProjectPublicApiController::projectStats missing per-route response decorator",
  "services/work-management/src/interface/http/report-public-api.controller.ts: ReportPublicApiController::burndown missing ApiOperation",
  "services/work-management/src/interface/http/report-public-api.controller.ts: ReportPublicApiController::burndown missing per-route response decorator",
  "services/work-management/src/interface/http/report-public-api.controller.ts: ReportPublicApiController::projectPage missing ApiOperation",
  "services/work-management/src/interface/http/report-public-api.controller.ts: ReportPublicApiController::projectPage missing per-route response decorator",
  "services/work-management/src/interface/http/report-public-api.controller.ts: ReportPublicApiController::velocity missing ApiOperation",
  "services/work-management/src/interface/http/report-public-api.controller.ts: ReportPublicApiController::velocity missing per-route response decorator",
  "services/work-management/src/interface/http/saved-view-public-api.controller.ts: SavedViewPublicApiController::createSavedView missing ApiOperation",
  "services/work-management/src/interface/http/saved-view-public-api.controller.ts: SavedViewPublicApiController::createSavedView missing per-route response decorator",
  "services/work-management/src/interface/http/saved-view-public-api.controller.ts: SavedViewPublicApiController::deleteSavedView missing ApiOperation",
  "services/work-management/src/interface/http/saved-view-public-api.controller.ts: SavedViewPublicApiController::deleteSavedView missing per-route response decorator",
  "services/work-management/src/interface/http/saved-view-public-api.controller.ts: SavedViewPublicApiController::getSavedView missing ApiOperation",
  "services/work-management/src/interface/http/saved-view-public-api.controller.ts: SavedViewPublicApiController::getSavedView missing per-route response decorator",
  "services/work-management/src/interface/http/saved-view-public-api.controller.ts: SavedViewPublicApiController::listSavedViews missing ApiOperation",
  "services/work-management/src/interface/http/saved-view-public-api.controller.ts: SavedViewPublicApiController::listSavedViews missing per-route response decorator",
  "services/work-management/src/interface/http/saved-view-public-api.controller.ts: SavedViewPublicApiController::patchSavedView missing ApiOperation",
  "services/work-management/src/interface/http/saved-view-public-api.controller.ts: SavedViewPublicApiController::patchSavedView missing per-route response decorator",
  "services/work-management/src/interface/http/sprint-public-api.controller.ts: SprintPublicApiController::addTask missing ApiOperation",
  "services/work-management/src/interface/http/sprint-public-api.controller.ts: SprintPublicApiController::addTask missing per-route response decorator",
  "services/work-management/src/interface/http/sprint-public-api.controller.ts: SprintPublicApiController::closeSprint missing ApiOperation",
  "services/work-management/src/interface/http/sprint-public-api.controller.ts: SprintPublicApiController::closeSprint missing per-route response decorator",
  "services/work-management/src/interface/http/sprint-public-api.controller.ts: SprintPublicApiController::createSprint missing ApiOperation",
  "services/work-management/src/interface/http/sprint-public-api.controller.ts: SprintPublicApiController::createSprint missing per-route response decorator",
  "services/work-management/src/interface/http/sprint-public-api.controller.ts: SprintPublicApiController::deleteSprint missing ApiOperation",
  "services/work-management/src/interface/http/sprint-public-api.controller.ts: SprintPublicApiController::deleteSprint missing per-route response decorator",
  "services/work-management/src/interface/http/sprint-public-api.controller.ts: SprintPublicApiController::getSprint missing ApiOperation",
  "services/work-management/src/interface/http/sprint-public-api.controller.ts: SprintPublicApiController::listSprints missing ApiOperation",
  "services/work-management/src/interface/http/sprint-public-api.controller.ts: SprintPublicApiController::listSprints missing per-route response decorator",
  "services/work-management/src/interface/http/sprint-public-api.controller.ts: SprintPublicApiController::patchSprint missing ApiOperation",
  "services/work-management/src/interface/http/sprint-public-api.controller.ts: SprintPublicApiController::removeTask missing ApiOperation",
  "services/work-management/src/interface/http/sprint-public-api.controller.ts: SprintPublicApiController::removeTask missing per-route response decorator",
  "services/work-management/src/interface/http/sprint-public-api.controller.ts: SprintPublicApiController::startSprint missing ApiOperation",
  "services/work-management/src/interface/http/sprint-public-api.controller.ts: SprintPublicApiController::startSprint missing per-route response decorator",
  "services/work-management/src/interface/http/task-public-api.controller.ts: TaskPublicApiController::bulkDeleteBoardWorkItems missing ApiOperation",
  "services/work-management/src/interface/http/task-public-api.controller.ts: TaskPublicApiController::bulkDeleteBoardWorkItems missing per-route response decorator",
  "services/work-management/src/interface/http/task-public-api.controller.ts: TaskPublicApiController::bulkUpdateBoardWorkItems missing ApiOperation",
  "services/work-management/src/interface/http/task-public-api.controller.ts: TaskPublicApiController::bulkUpdateBoardWorkItems missing per-route response decorator",
  "services/work-management/src/interface/http/task-public-api.controller.ts: TaskPublicApiController::exportTasksCsv missing ApiOperation",
  "services/work-management/src/interface/http/task-public-api.controller.ts: TaskPublicApiController::exportTasksCsv missing per-route response decorator",
  "services/work-management/src/interface/http/task-public-api.controller.ts: TaskPublicApiController::importTasksCsv missing ApiOperation",
  "services/work-management/src/interface/http/task-public-api.controller.ts: TaskPublicApiController::importTasksCsv missing per-route response decorator",
  "services/work-management/src/interface/http/task-public-api.controller.ts: TaskPublicApiController::listTaskChildren missing ApiOperation",
  "services/work-management/src/interface/http/task-public-api.controller.ts: TaskPublicApiController::listTaskChildren missing per-route response decorator",
  "services/work-management/src/interface/http/task-public-api.controller.ts: TaskPublicApiController::manualTaskWorkbench missing ApiOperation",
  "services/work-management/src/interface/http/task-public-api.controller.ts: TaskPublicApiController::manualTaskWorkbench missing per-route response decorator",
  "services/work-management/src/interface/http/task-public-api.controller.ts: TaskPublicApiController::setTaskDependencies missing ApiOperation",
  "services/work-management/src/interface/http/task-public-api.controller.ts: TaskPublicApiController::setTaskDependencies missing per-route response decorator",
  "services/work-management/src/interface/http/task-public-api.controller.ts: TaskPublicApiController::setTaskParent missing ApiOperation",
  "services/work-management/src/interface/http/task-public-api.controller.ts: TaskPublicApiController::setTaskParent missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::acceptArtifact missing ApiOperation",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::acceptArtifact missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::archiveArtifact missing ApiOperation",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::archiveArtifact missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::deleteArtifact missing ApiOperation",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::deleteArtifact missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::downloadArtifact missing ApiOperation",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::downloadArtifact missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::getArtifact missing ApiOperation",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::getArtifact missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::listArtifacts missing ApiOperation",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::listArtifacts missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::rejectArtifact missing ApiOperation",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::rejectArtifact missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::unarchiveArtifact missing ApiOperation",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::unarchiveArtifact missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::uploadArtifact missing ApiOperation",
  "services/workflow-coordination/src/interface/http/artifact-public-api.controller.ts: ArtifactPublicApiController::uploadArtifact missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/audit-public-api.controller.ts: AuditPublicApiController::exportAuditEvents missing ApiOperation",
  "services/workflow-coordination/src/interface/http/audit-public-api.controller.ts: AuditPublicApiController::exportAuditEvents missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/audit-public-api.controller.ts: AuditPublicApiController::getExportStatus missing ApiOperation",
  "services/workflow-coordination/src/interface/http/audit-public-api.controller.ts: AuditPublicApiController::getExportStatus missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/audit-public-api.controller.ts: AuditPublicApiController::getRetentionPolicy missing ApiOperation",
  "services/workflow-coordination/src/interface/http/audit-public-api.controller.ts: AuditPublicApiController::getRetentionPolicy missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/audit-public-api.controller.ts: AuditPublicApiController::listAuditEvents missing ApiOperation",
  "services/workflow-coordination/src/interface/http/audit-public-api.controller.ts: AuditPublicApiController::listAuditEvents missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/audit-public-api.controller.ts: AuditPublicApiController::listRetentionPolicies missing ApiOperation",
  "services/workflow-coordination/src/interface/http/audit-public-api.controller.ts: AuditPublicApiController::listRetentionPolicies missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/audit-public-api.controller.ts: AuditPublicApiController::setRetentionPolicy missing ApiOperation",
  "services/workflow-coordination/src/interface/http/audit-public-api.controller.ts: AuditPublicApiController::setRetentionPolicy missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/dependency-execution.controller.ts: DependencyExecutionController::dispatchDependencyRun missing ApiOperation",
  "services/workflow-coordination/src/interface/http/dependency-execution.controller.ts: DependencyExecutionController::dispatchDependencyRun missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/dependency-execution.controller.ts: DependencyExecutionController::loadDependencyRunLiveFeedback missing ApiOperation",
  "services/workflow-coordination/src/interface/http/dependency-execution.controller.ts: DependencyExecutionController::loadDependencyRunLiveFeedback missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/dependency-execution.controller.ts: DependencyExecutionController::previewDependencyRun missing ApiOperation",
  "services/workflow-coordination/src/interface/http/dependency-execution.controller.ts: DependencyExecutionController::previewDependencyRun missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/dependency-execution.controller.ts: DependencyExecutionController::recordDependencyRunLifecycleEvent missing ApiOperation",
  "services/workflow-coordination/src/interface/http/dependency-execution.controller.ts: DependencyExecutionController::recordDependencyRunLifecycleEvent missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/dependency-execution.controller.ts: DependencyExecutionController::recordTaskQaReview missing ApiOperation",
  "services/workflow-coordination/src/interface/http/dependency-execution.controller.ts: DependencyExecutionController::recordTaskQaReview missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/dependency-execution.controller.ts: DependencyExecutionController::runAutomatedFeedbackLoop missing ApiOperation",
  "services/workflow-coordination/src/interface/http/dependency-execution.controller.ts: DependencyExecutionController::runAutomatedFeedbackLoop missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/dependency-execution.controller.ts: DependencyExecutionController::runDependencyRunWorkerTick missing ApiOperation",
  "services/workflow-coordination/src/interface/http/dependency-execution.controller.ts: DependencyExecutionController::runDependencyRunWorkerTick missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/dependency-execution.controller.ts: DependencyExecutionController::streamDependencyRunLiveFeedback missing ApiOperation",
  "services/workflow-coordination/src/interface/http/dependency-execution.controller.ts: DependencyExecutionController::streamDependencyRunLiveFeedback missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/document-workspace.controller.ts: DocumentWorkspaceController::previewPageOperations missing ApiOperation",
  "services/workflow-coordination/src/interface/http/document-workspace.controller.ts: DocumentWorkspaceController::previewPageOperations missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/document-workspace.controller.ts: DocumentWorkspaceController::previewPageTree missing ApiOperation",
  "services/workflow-coordination/src/interface/http/document-workspace.controller.ts: DocumentWorkspaceController::previewPageTree missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::buildFreeformDocsPlanningPrompt missing ApiOperation",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::buildFreeformDocsPlanningPrompt missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::generateTechnicalPlanningCycle missing ApiOperation",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::generateTechnicalPlanningCycle missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::materializeApprovedPlan missing ApiOperation",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::materializeApprovedPlan missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::previewApprovedPlan missing ApiOperation",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::previewApprovedPlan missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::recordArtifactExecution missing ApiOperation",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::recordArtifactExecution missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::recordGuidedAcpSessionAction missing ApiOperation",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::recordGuidedAcpSessionAction missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::restartPlanningCycleFromUpdates missing ApiOperation",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::restartPlanningCycleFromUpdates missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::runArtifactExecution missing ApiOperation",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::runArtifactExecution missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::startFreeformWork missing ApiOperation",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::startFreeformWork missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::startGuidedAcpPlanning missing ApiOperation",
  "services/workflow-coordination/src/interface/http/planning-preview.controller.ts: PlanningPreviewController::startGuidedAcpPlanning missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::appendReviewWorkbenchAnnotation missing ApiOperation",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::appendReviewWorkbenchAnnotation missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::applyConfiguredUatCodeReviewDecision missing ApiOperation",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::applyConfiguredUatCodeReviewDecision missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::buildFinalQaFeedbackGate missing ApiOperation",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::buildFinalQaFeedbackGate missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::buildFinalQaReport missing ApiOperation",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::buildFinalQaReport missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::buildUatCodeReviewHandoff missing ApiOperation",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::buildUatCodeReviewHandoff missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::listGeneratedE2eRuns missing ApiOperation",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::listGeneratedE2eRuns missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::loadReviewWorkbenchSession missing ApiOperation",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::loadReviewWorkbenchSession missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::previewWorkbench missing ApiOperation",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::previewWorkbench missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::recordUatCodeReviewDecision missing ApiOperation",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::recordUatCodeReviewDecision missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::runGeneratedE2eRegressionTests missing ApiOperation",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::runGeneratedE2eRegressionTests missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::saveReviewWorkbenchSession missing ApiOperation",
  "services/workflow-coordination/src/interface/http/review-workbench.controller.ts: ReviewWorkbenchController::saveReviewWorkbenchSession missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/work-context.controller.ts: WorkContextController::loadContextTrace missing ApiOperation",
  "services/workflow-coordination/src/interface/http/work-context.controller.ts: WorkContextController::loadContextTrace missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/work-context.controller.ts: WorkContextController::persistContextTrace missing ApiOperation",
  "services/workflow-coordination/src/interface/http/work-context.controller.ts: WorkContextController::persistContextTrace missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/workflow-cycle.controller.ts: WorkflowCycleController::loadTraceSummary missing ApiOperation",
  "services/workflow-coordination/src/interface/http/workflow-cycle.controller.ts: WorkflowCycleController::loadTraceSummary missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/workflow-cycle.controller.ts: WorkflowCycleController::persistCycle missing ApiOperation",
  "services/workflow-coordination/src/interface/http/workflow-cycle.controller.ts: WorkflowCycleController::persistCycle missing per-route response decorator",
  "services/workflow-coordination/src/interface/http/workflow-cycle.controller.ts: WorkflowCycleController::runAcceptanceCycle missing ApiOperation",
  "services/workflow-coordination/src/interface/http/workflow-cycle.controller.ts: WorkflowCycleController::runAcceptanceCycle missing per-route response decorator",
] as const;
