import { extractRouterMetadata, type DomainMetadata } from "../../scripts/cli/codegen.ts";

export type CompletionShell = "bash" | "zsh" | "fish";

export type CompletionScripts = Record<CompletionShell, string>;

export type GenerateCompletionScriptsOptions = {
  routerPath: string;
};

type CompletionCommand = {
  name: string;
  verbs: string[];
  flags: string[];
  dynamicIdSource: string | null;
};

export async function generateCompletionScripts(
  options: GenerateCompletionScriptsOptions,
): Promise<CompletionScripts> {
  return emitCompletionScripts(await extractRouterMetadata(options.routerPath));
}

export function emitCompletionScripts(domains: DomainMetadata[]): CompletionScripts {
  const commands = domains
    .filter((domain) => domain.procedures.length > 0)
    .map(domainCompletion)
    .sort((a, b) => a.name.localeCompare(b.name));

  return {
    bash: emitBash(commands),
    zsh: emitZsh(commands),
    fish: emitFish(commands),
  };
}

export async function printCompletionScript(
  shell: CompletionShell,
  options: GenerateCompletionScriptsOptions,
): Promise<void> {
  const scripts = await generateCompletionScripts(options);
  process.stdout.write(scripts[shell]);
}

function domainCompletion(domain: DomainMetadata): CompletionCommand {
  return {
    name: domain.name,
    verbs: uniqueSorted(domain.procedures.map((procedure) => procedure.path.map(kebab).join(" "))),
    flags: uniqueSorted(domain.procedures.flatMap((procedure) => procedureFlags(procedure))),
    dynamicIdSource: domain.procedures.some((procedure) => procedure.path.join(".") === "list") ? domain.name : null,
  };
}

function procedureFlags(procedure: DomainMetadata["procedures"][number]): string[] {
  const flags = ["--json"];
  if (procedure.type === "subscription") flags.push("--watch");
  return flags;
}

function emitBash(commands: CompletionCommand[]): string {
  const domains = commands.map((command) => command.name);
  const lines = [
    "# bash completion for fulcrum",
    "# Generated by scripts/cli/codegen.ts.",
    "_fulcrum_dynamic_ids() {",
    "  local domain=\"$1\"",
    "  command fulcrum \"$domain\" list --json 2>/dev/null | jq -r '.[]?.id // empty' 2>/dev/null || true",
    "}",
    "",
    "_fulcrum() {",
    "  local cur prev domain",
    "  COMPREPLY=()",
    "  cur=\"${COMP_WORDS[COMP_CWORD]}\"",
    "  prev=\"${COMP_WORDS[COMP_CWORD-1]}\"",
    "  domain=\"${COMP_WORDS[1]}\"",
    "  if [[ ${COMP_CWORD} -eq 1 ]]; then",
    `    COMPREPLY=( $(compgen -W ${shellWords(domains)} -- "$cur") )`,
    "    return 0",
    "  fi",
    "  case \"$domain\" in",
  ];

  for (const command of commands) {
    lines.push(`    ${bashCase(command.name)})`);
    lines.push(`      local verbs=${shellWords(command.verbs)}`);
    lines.push(`      local flags=${shellWords(command.flags)}`);
    lines.push("      if [[ \"$cur\" == --* ]]; then");
    lines.push("        COMPREPLY=( $(compgen -W \"$flags\" -- \"$cur\") )");
    lines.push("        return 0");
    lines.push("      fi");
    if (command.dynamicIdSource !== null) {
      lines.push("      if [[ \"$prev\" == \"get\" || \"$prev\" == \"delete\" || \"$prev\" == \"update\" ]]; then");
      lines.push(`        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids ${bashQuote(command.dynamicIdSource)})" -- "$cur") )`);
      lines.push("        return 0");
      lines.push("      fi");
    }
    lines.push("      COMPREPLY=( $(compgen -W \"$verbs $flags\" -- \"$cur\") )");
    lines.push("      ;;");
  }

  lines.push("  esac");
  lines.push("}");
  lines.push("complete -F _fulcrum fulcrum");
  lines.push("");
  return lines.join("\n");
}

function emitZsh(commands: CompletionCommand[]): string {
  const domainSpecs = commands.map((command) => `${command.name}:fulcrum ${command.name}`);
  const lines = [
    "#compdef fulcrum",
    "# zsh completion for fulcrum",
    "# Generated by scripts/cli/codegen.ts.",
    "_fulcrum_dynamic_ids() {",
    "  command fulcrum \"$1\" list --json 2>/dev/null | jq -r '.[]?.id // empty' 2>/dev/null || true",
    "}",
    "",
    "_fulcrum() {",
    "  local -a domains",
    `  domains=(${zshSpecs(domainSpecs)})`,
    "  if (( CURRENT == 2 )); then",
    "    _describe 'fulcrum command' domains",
    "    return",
    "  fi",
    "  case $words[2] in",
  ];

  for (const command of commands) {
    const specs = [
      ...command.verbs.map((verb) => `${verb}:fulcrum ${command.name} ${verb}`),
      ...command.flags.map((flag) => `${flag}:option`),
    ];
    lines.push(`    ${zshCase(command.name)})`);
    lines.push(`      local -a values=(${zshSpecs(specs)})`);
    if (command.dynamicIdSource !== null) {
      lines.push("      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then");
      lines.push(`        _values 'ids' $(_fulcrum_dynamic_ids ${zshQuote(command.dynamicIdSource)})`);
      lines.push("        return");
      lines.push("      fi");
    }
    lines.push("      _describe 'command or option' values");
    lines.push("      ;;");
  }

  lines.push("  esac");
  lines.push("}");
  lines.push("_fulcrum \"$@\"");
  lines.push("");
  return lines.join("\n");
}

function emitFish(commands: CompletionCommand[]): string {
  const lines = [
    "# fish completion for fulcrum",
    "# Generated by scripts/cli/codegen.ts.",
    "function __fulcrum_dynamic_ids",
    "    command fulcrum $argv[1] list --json 2>/dev/null | jq -r '.[]?.id // empty' 2>/dev/null",
    "end",
    "",
  ];

  for (const command of commands) {
    lines.push(`complete -c fulcrum -n "__fish_use_subcommand" -a ${fishQuote(command.name)} -d ${fishQuote(`fulcrum ${command.name}`)}`);
    for (const verb of command.verbs) {
      lines.push(`complete -c fulcrum -n "__fish_seen_subcommand_from ${fishQuote(command.name)}" -a ${fishQuote(verb)} -d ${fishQuote(`${command.name} ${verb}`)}`);
    }
    for (const flag of command.flags) {
      lines.push(`complete -c fulcrum -n "__fish_seen_subcommand_from ${fishQuote(command.name)}" -l ${fishFlag(flag)} -d option`);
    }
    if (command.dynamicIdSource !== null) {
      lines.push(`complete -c fulcrum -n "__fish_seen_subcommand_from ${fishQuote(command.name)}; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids ${fishQuote(command.name)})"`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

function uniqueSorted(values: string[]): string[] {
  return [...new Set(values)].sort((a, b) => a.localeCompare(b));
}

function kebab(value: string): string {
  return value.replaceAll("_", "-").replace(/[A-Z]/g, (char) => `-${char.toLowerCase()}`).replace(/^-/, "");
}

function shellWords(values: string[]): string {
  return bashQuote(values.join(" "));
}

function bashCase(value: string): string {
  return value.replace(/([\\()*?[\]{}|;&<>`$! ])/g, "\\$1");
}

function bashQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function zshCase(value: string): string {
  return value.replace(/([\\()*?[\]{}|;&<>`$! ])/g, "\\$1");
}

function zshSpecs(values: string[]): string {
  return values.map(zshQuote).join(" ");
}

function zshQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''").replaceAll("[", "\\[").replaceAll("]", "\\]")}'`;
}

function fishQuote(value: string): string {
  return `'${value.replaceAll("\\", "\\\\").replaceAll("'", "\\'")}'`;
}

function fishFlag(flag: string): string {
  return flag.replace(/^--/, "");
}
