/**
 * Minimal PGlite Kysely dialect + driver adapter for MikroORM v7.
 *
 * MikroORM v7 replaced Knex with Kysely. The community `mikro-orm-pglite@0.5.1`
 * package still targets v6 (Knex-based). This file bridges the gap by implementing
 * the four Kysely interfaces (Dialect, Driver, DatabaseConnection, DialectAdapter)
 * around PGlite's query API.
 *
 * PGlite does NOT support multiple statements in a single prepared query,
 * so we split on semicolons and execute each statement sequentially.
 *
 * C6: No plaintext SQL in production code — this file only bridges the driver layer.
 *     The actual SQL is generated by MikroORM's QueryBuilder/schema generator.
 */

import type {
  DatabaseConnection,
  Dialect,
  DialectAdapter,
  Driver,
  QueryResult,
} from "kysely";
import { type CompiledQuery, CompiledQuery as CQ } from "kysely";
import {
  PostgresAdapter,
  PostgresIntrospector,
  PostgresQueryCompiler,
} from "kysely";
import type { Kysely } from "kysely";
import type { PGlite } from "@electric-sql/pglite";

/**
 * Splits a SQL string containing multiple semicolon-separated statements
 * into individual statements (skipping empty strings).
 *
 * This is intentionally simple (split on ';') because MikroORM's schema generator
 * only sends DDL statements here, which do not contain semicolons inside string
 * literals. For parameterised DML the single-statement path is used instead.
 */
function splitStatements(sql: string): string[] {
  return sql
    .split(";")
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

// ── DatabaseConnection ──────────────────────────────────────────────────────

class PGliteConnection implements DatabaseConnection {
  constructor(private readonly pglite: PGlite) {}

  async executeQuery<R>(compiledQuery: CompiledQuery): Promise<QueryResult<R>> {
    const { sql, parameters } = compiledQuery;

    // PGlite does not support multiple statements in a single prepared query.
    // Detect multi-statement SQL (contains ';\n' or ';\r\n') and use exec() instead,
    // which handles multiple statements but doesn't support parameterised queries.
    // Single-statement queries use the parameterised query() path for safety.
    const stmts = splitStatements(sql);
    if (stmts.length === 0) return { rows: [] };

    if (stmts.length > 1) {
      // Multi-statement DDL: PGlite's exec() handles multiple commands.
      // Parameters are not supported in multi-statement DDL.
      const results = await this.pglite.exec(stmts.join(";"));
      const last = results[results.length - 1];
      return {
        rows: (last?.rows ?? []) as R[],
        numAffectedRows: BigInt(last?.affectedRows ?? 0),
      };
    }

    // Single statement — use parameterised query for DML
    const result = await this.pglite.query<R>(sql, parameters as unknown[]);
    return {
      rows: result.rows,
      numAffectedRows: BigInt(result.affectedRows ?? 0),
    };
  }

  // eslint-disable-next-line require-yield
  async *streamQuery<R>(): AsyncIterableIterator<QueryResult<R>> {
    throw new Error("PGliteConnection: streamQuery not supported");
  }
}

// ── Driver ──────────────────────────────────────────────────────────────────

class PGliteKyselyDriver implements Driver {
  private conn: PGliteConnection | null = null;

  constructor(private readonly getPglite: () => Promise<PGlite> | PGlite) {}

  async init(): Promise<void> {
    const pg = await this.getPglite();
    await pg.waitReady;
    this.conn = new PGliteConnection(pg);
  }

  async acquireConnection(): Promise<DatabaseConnection> {
    if (!this.conn) throw new Error("PGliteKyselyDriver: not initialized");
    return this.conn;
  }

  async beginTransaction(connection: DatabaseConnection): Promise<void> {
    await connection.executeQuery(CQ.raw("BEGIN"));
  }

  async commitTransaction(connection: DatabaseConnection): Promise<void> {
    await connection.executeQuery(CQ.raw("COMMIT"));
  }

  async rollbackTransaction(connection: DatabaseConnection): Promise<void> {
    await connection.executeQuery(CQ.raw("ROLLBACK"));
  }

  async releaseConnection(): Promise<void> {
    // PGlite has one shared connection — nothing to release
  }

  async destroy(): Promise<void> {
    // Lifecycle owned externally — caller manages PGlite.close()
  }
}

// ── Dialect ─────────────────────────────────────────────────────────────────

export class PGliteKyselyDialect implements Dialect {
  constructor(private readonly getPglite: () => Promise<PGlite> | PGlite) {}

  createDriver(): Driver {
    return new PGliteKyselyDriver(this.getPglite);
  }

  createQueryCompiler() {
    return new PostgresQueryCompiler();
  }

  createAdapter(): DialectAdapter {
    return new PostgresAdapter();
  }

  createIntrospector(db: Kysely<unknown>) {
    return new PostgresIntrospector(db);
  }
}
