/**
 * Minimal PGlite Kysely dialect + driver adapter for MikroORM v7.
 *
 * MikroORM v7 replaced Knex with Kysely. The community `mikro-orm-pglite@0.5.1`
 * package still targets v6 (Knex-based). This file bridges the gap by implementing
 * the four Kysely interfaces (Dialect, Driver, DatabaseConnection, DialectAdapter)
 * around PGlite's query API.
 *
 * C6: No plaintext SQL in production code — this file only bridges the driver layer.
 *     The actual SQL is generated by MikroORM's QueryBuilder/schema generator.
 */

import type {
  DatabaseConnection,
  Dialect,
  DialectAdapter,
  Driver,
  QueryResult,
} from "kysely";
import { type CompiledQuery, CompiledQuery as CQ } from "kysely";
import {
  PostgresAdapter,
  PostgresIntrospector,
  PostgresQueryCompiler,
} from "kysely";
import type { Kysely } from "kysely";
import type { PGlite } from "@electric-sql/pglite";

/**
 * Quote-aware SQL statement splitter.
 *
 * Splits a multi-statement DDL string into individual statements, correctly
 * handling single-quoted strings ('…'), double-quoted identifiers ("…"), and
 * dollar-quoted blocks ($tag$…$tag$).  A semicolon that appears inside any of
 * these quoting forms is NOT treated as a statement boundary.
 *
 * Limitations: C-style block comments (/* … *\/) are not tracked, but MikroORM's
 * schema generator never emits them, so this is a non-issue for our use-case.
 *
 * @returns Array of trimmed, non-empty SQL statements (without trailing `;`).
 */
export function splitStatements(sql: string): string[] {
  const stmts: string[] = [];
  let current = "";
  let i = 0;

  while (i < sql.length) {
    const ch = sql[i]!;

    // Single-quoted string literal: scan until closing ' (handle '' escapes)
    if (ch === "'") {
      current += ch;
      i++;
      while (i < sql.length) {
        const c = sql[i]!;
        current += c;
        i++;
        if (c === "'") {
          // Check for escaped quote '' — if next char is also ' it's an escape
          if (sql[i] === "'") {
            current += sql[i]!;
            i++;
          } else {
            break; // closing quote
          }
        }
      }
      continue;
    }

    // Double-quoted identifier: scan until closing "
    if (ch === '"') {
      current += ch;
      i++;
      while (i < sql.length) {
        const c = sql[i]!;
        current += c;
        i++;
        if (c === '"') {
          // Handle "" escape inside identifier
          if (sql[i] === '"') {
            current += sql[i]!;
            i++;
          } else {
            break;
          }
        }
      }
      continue;
    }

    // Dollar-quoted block: $tag$…$tag$ where tag may be empty ($$ … $$)
    if (ch === "$") {
      // Try to read the dollar-quote tag: $[A-Za-z0-9_]*$
      let tag = "$";
      let j = i + 1;
      while (j < sql.length && sql[j] !== "$" && /\w/.test(sql[j]!)) {
        tag += sql[j]!;
        j++;
      }
      if (j < sql.length && sql[j] === "$") {
        tag += "$"; // complete the opening tag, e.g. "$$" or "$body$"
        const closeTag = tag;
        current += tag;
        i = j + 1;
        // Scan for the matching closing tag
        while (i < sql.length) {
          const closeIdx = sql.indexOf(closeTag, i);
          if (closeIdx === -1) {
            // No closing tag found — consume rest of string (malformed SQL)
            current += sql.slice(i);
            i = sql.length;
            break;
          }
          current += sql.slice(i, closeIdx + closeTag.length);
          i = closeIdx + closeTag.length;
          break;
        }
        continue;
      }
      // Not a dollar-quote — fall through as regular character
    }

    // Statement boundary
    if (ch === ";") {
      const stmt = current.trim();
      if (stmt.length > 0) {
        stmts.push(stmt);
      }
      current = "";
      i++;
      continue;
    }

    current += ch;
    i++;
  }

  // Handle final statement without trailing semicolon
  const remaining = current.trim();
  if (remaining.length > 0) {
    stmts.push(remaining);
  }

  return stmts;
}

// ── DatabaseConnection ──────────────────────────────────────────────────────

class PGliteConnection implements DatabaseConnection {
  constructor(private readonly pglite: PGlite) {}

  async executeQuery<R>(compiledQuery: CompiledQuery): Promise<QueryResult<R>> {
    const { sql, parameters } = compiledQuery;

    // PGlite does not support multiple statements in a single prepared query.
    // Use the quote-aware splitter to detect multi-statement DDL.
    const stmts = splitStatements(sql);
    if (stmts.length === 0) return { rows: [] };

    if (stmts.length > 1) {
      // Multi-statement DDL: PGlite's exec() handles multiple commands.
      // Parameters are not supported in multi-statement DDL.
      const results = await this.pglite.exec(stmts.join(";"));
      const last = results[results.length - 1];
      return {
        rows: (last?.rows ?? []) as R[],
        numAffectedRows: BigInt(last?.affectedRows ?? 0),
      };
    }

    // Single statement — use parameterised query for DML
    const result = await this.pglite.query<R>(sql, parameters as unknown[]);
    return {
      rows: result.rows,
      numAffectedRows: BigInt(result.affectedRows ?? 0),
    };
  }

  // eslint-disable-next-line require-yield
  async *streamQuery<R>(): AsyncIterableIterator<QueryResult<R>> {
    throw new Error("PGliteConnection: streamQuery not supported");
  }
}

// ── Driver ──────────────────────────────────────────────────────────────────

class PGliteKyselyDriver implements Driver {
  private conn: PGliteConnection | null = null;

  constructor(private readonly getPglite: () => Promise<PGlite> | PGlite) {}

  async init(): Promise<void> {
    const pg = await this.getPglite();
    await pg.waitReady;
    this.conn = new PGliteConnection(pg);
  }

  async acquireConnection(): Promise<DatabaseConnection> {
    if (!this.conn) throw new Error("PGliteKyselyDriver: not initialized");
    return this.conn;
  }

  async beginTransaction(connection: DatabaseConnection): Promise<void> {
    await connection.executeQuery(CQ.raw("BEGIN"));
  }

  async commitTransaction(connection: DatabaseConnection): Promise<void> {
    await connection.executeQuery(CQ.raw("COMMIT"));
  }

  async rollbackTransaction(connection: DatabaseConnection): Promise<void> {
    await connection.executeQuery(CQ.raw("ROLLBACK"));
  }

  async releaseConnection(): Promise<void> {
    // PGlite has one shared connection — nothing to release
  }

  async destroy(): Promise<void> {
    // Lifecycle owned externally — caller manages PGlite.close()
  }
}

// ── Dialect ─────────────────────────────────────────────────────────────────

export class PGliteKyselyDialect implements Dialect {
  constructor(private readonly getPglite: () => Promise<PGlite> | PGlite) {}

  createDriver(): Driver {
    return new PGliteKyselyDriver(this.getPglite);
  }

  createQueryCompiler() {
    return new PostgresQueryCompiler();
  }

  createAdapter(): DialectAdapter {
    return new PostgresAdapter();
  }

  createIntrospector(db: Kysely<unknown>) {
    return new PostgresIntrospector(db);
  }
}
