# bash completion for fulcrum
# Generated by scripts/cli/codegen.ts.
_fulcrum_dynamic_ids() {
  local domain="$1"
  command fulcrum "$domain" list --json 2>/dev/null | jq -r '.[]?.id // empty' 2>/dev/null || true
}

_fulcrum() {
  local cur prev domain
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  domain="${COMP_WORDS[1]}"
  if [[ ${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W 'agent_runs agents artifacts audit auth automations backup comments connectors context credentials customFieldDefs dataExport dataImport db doc_comments doc_links doc_versions docs doctor errorLogs flags fulcrum_skills health inference invitations memories notify notifySubscriptions orchestrationSubscriptions orgs planning projects recurrence relationships repo_branches repo_commits reports repos review routing runsSubscriptions saved_views search sprints taskCustomFields tasks telemetry templates theme webhooks workflows' -- "$cur") )
    return 0
  fi
  case "$domain" in
    agent_runs)
      local verbs='cancel create get list retry'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'agent_runs')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    agents)
      local verbs='get-profile list-profiles test-profile'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    artifacts)
      local verbs='accept archive delete download get list reject unarchive upload'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'artifacts')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    audit)
      local verbs='export query retention-policy get retention-policy list retention-policy set'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    auth)
      local verbs='accept-invite invite whoami'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    automations)
      local verbs='create delete list templates update'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'automations')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    backup)
      local verbs='create restore'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    comments)
      local verbs='add-reaction create delete list remove-reaction resolve subscribe threaded unresolve unsubscribe watchers'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'comments')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    connectors)
      local verbs='disable enable get list runs get runs list sync'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'connectors')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    context)
      local verbs='assemble preview'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    credentials)
      local verbs='archive get list remove rotate set'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'credentials')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    customFieldDefs)
      local verbs='list'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'customFieldDefs')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    dataExport)
      local verbs='create'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    dataImport)
      local verbs='preflight run'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    db)
      local verbs='ping'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    doc_comments)
      local verbs='create delete list resolve update'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'doc_comments')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    doc_links)
      local verbs='create delete list'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'doc_links')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    doc_versions)
      local verbs='diff get list restore'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'doc_versions')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    docs)
      local verbs='comments create comments delete comments list comments resolve comments update create delete get links list-backlinks links list-forward-links list templates list templates resolve update versions diff versions get versions list versions restore'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'docs')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    doctor)
      local verbs='run subsystems'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    errorLogs)
      local verbs='clear get list'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'errorLogs')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    flags)
      local verbs='evaluate experiments assignments experiments create experiments list experiments metrics list set set-override set-rollout'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'flags')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    fulcrum_skills)
      local verbs='conflicts list conflicts override install list lock override registry list resolve-conflict sync uninstall upgrade'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'fulcrum_skills')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    health)
      local verbs='ping'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    inference)
      local verbs='backends list backends probe classify config get config set embed generate health models list models pull models rm provider set provider test tokenize'
      local flags='--json --watch'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    invitations)
      local verbs='create get list revoke'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'invitations')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    memories)
      local verbs='create delete get list promote search update'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'memories')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    notify)
      local verbs='channels config channels list channels test list mark-all-read mark-read mute mutes list quiet-hours get quiet-hours set rules create rules delete rules get rules list rules update unmute unread-count'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'notify')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    notifySubscriptions)
      local verbs='on-new-notification'
      local flags='--json --watch'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    orchestrationSubscriptions)
      local verbs='on-state-change'
      local flags='--json --watch'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    orgs)
      local verbs='get members list members remove members update-role update'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    planning)
      local verbs='build-freeform-docs-planning-prompt generate-technical-planning-cycle materialize-approved-plan-breakdown preview-approved-plan-breakdown restart-planning-cycle-from-updates start-freeform-work-from-docs start-guided-acp-planning-session'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    projects)
      local verbs='create delete get list stats update'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'projects')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    recurrence)
      local verbs='create delete list'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'recurrence')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    relationships)
      local verbs='blocked-items blockers create delete list-blocked-by list-for-task mark-as-duplicate summary'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    repo_branches)
      local verbs='get list'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'repo_branches')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    repo_commits)
      local verbs='get list'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'repo_commits')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    reports)
      local verbs='blocked-items burndown burnup cfd cycle-time export-csv lead-time progress-rollup stale-issues throughput velocity wip-over-time workload'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    repos)
      local verbs='get list register status-repo sync sync-repo unregister'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'repos')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    review)
      local verbs='apply-auto-decision build-uat-handoff record-uat-decision'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    routing)
      local verbs='config update-llm-gate create delete drafts approve drafts delete drafts list drafts update dry-run get list test update'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'routing')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    runsSubscriptions)
      local verbs='on-run-update'
      local flags='--json --watch'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    saved_views)
      local verbs='create delete get list update'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'saved_views')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    search)
      local verbs='query record-click saved-create saved-delete saved-list saved-update snapshot suggest'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    sprints)
      local verbs='add-task close create delete get list remove-task start update'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'sprints')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    taskCustomFields)
      local verbs='clear set'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    tasks)
      local verbs='bulk-delete bulk-update create delete dependency-run-live-feedback dependency-run-live-feedback-stream dispatch-dependency-run get list list-children manual-workbench preview-dependency-run record-qa-review run-automated-feedback-loop run-dependency-run-worker-tick set-dependencies set-parent update'
      local flags='--json --watch'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'tasks')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    telemetry)
      local verbs='opt-in opt-out purge status'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    templates)
      local verbs='apply-template create delete list set-default'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'templates')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    theme)
      local verbs='get get-theme list-themes set-theme update'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    webhooks)
      local verbs='create delete deliveries get deliveries list get list update'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      if [[ "$prev" == "get" || "$prev" == "delete" || "$prev" == "update" ]]; then
        COMPREPLY=( $(compgen -W "$(_fulcrum_dynamic_ids 'webhooks')" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
    workflows)
      local verbs='get-default get-enabled-task-types get-methodology get-transitions run-acceptance-cycle update-enabled-task-types update-methodology update-transitions validate-transition'
      local flags='--json'
      if [[ "$cur" == --* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        return 0
      fi
      COMPREPLY=( $(compgen -W "$verbs $flags" -- "$cur") )
      ;;
  esac
}
complete -F _fulcrum fulcrum
