# fish completion for fulcrum
# Generated by scripts/cli/codegen.ts.
function __fulcrum_dynamic_ids
    command fulcrum $argv[1] list --json 2>/dev/null | jq -r '.[]?.id // empty' 2>/dev/null
end

complete -c fulcrum -n "__fish_use_subcommand" -a 'agent_runs' -d 'fulcrum agent_runs'
complete -c fulcrum -n "__fish_seen_subcommand_from 'agent_runs'" -a 'cancel' -d 'agent_runs cancel'
complete -c fulcrum -n "__fish_seen_subcommand_from 'agent_runs'" -a 'create' -d 'agent_runs create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'agent_runs'" -a 'get' -d 'agent_runs get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'agent_runs'" -a 'list' -d 'agent_runs list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'agent_runs'" -a 'retry' -d 'agent_runs retry'
complete -c fulcrum -n "__fish_seen_subcommand_from 'agent_runs'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'agent_runs'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'agent_runs')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'agents' -d 'fulcrum agents'
complete -c fulcrum -n "__fish_seen_subcommand_from 'agents'" -a 'get-profile' -d 'agents get-profile'
complete -c fulcrum -n "__fish_seen_subcommand_from 'agents'" -a 'list-profiles' -d 'agents list-profiles'
complete -c fulcrum -n "__fish_seen_subcommand_from 'agents'" -a 'test-profile' -d 'agents test-profile'
complete -c fulcrum -n "__fish_seen_subcommand_from 'agents'" -l json -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'artifacts' -d 'fulcrum artifacts'
complete -c fulcrum -n "__fish_seen_subcommand_from 'artifacts'" -a 'archive' -d 'artifacts archive'
complete -c fulcrum -n "__fish_seen_subcommand_from 'artifacts'" -a 'delete' -d 'artifacts delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'artifacts'" -a 'download' -d 'artifacts download'
complete -c fulcrum -n "__fish_seen_subcommand_from 'artifacts'" -a 'get' -d 'artifacts get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'artifacts'" -a 'list' -d 'artifacts list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'artifacts'" -a 'unarchive' -d 'artifacts unarchive'
complete -c fulcrum -n "__fish_seen_subcommand_from 'artifacts'" -a 'upload' -d 'artifacts upload'
complete -c fulcrum -n "__fish_seen_subcommand_from 'artifacts'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'artifacts'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'artifacts')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'audit' -d 'fulcrum audit'
complete -c fulcrum -n "__fish_seen_subcommand_from 'audit'" -a 'export' -d 'audit export'
complete -c fulcrum -n "__fish_seen_subcommand_from 'audit'" -a 'query' -d 'audit query'
complete -c fulcrum -n "__fish_seen_subcommand_from 'audit'" -a 'retention-policy get' -d 'audit retention-policy get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'audit'" -a 'retention-policy list' -d 'audit retention-policy list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'audit'" -a 'retention-policy set' -d 'audit retention-policy set'
complete -c fulcrum -n "__fish_seen_subcommand_from 'audit'" -l json -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'auth' -d 'fulcrum auth'
complete -c fulcrum -n "__fish_seen_subcommand_from 'auth'" -a 'accept-invite' -d 'auth accept-invite'
complete -c fulcrum -n "__fish_seen_subcommand_from 'auth'" -a 'invite' -d 'auth invite'
complete -c fulcrum -n "__fish_seen_subcommand_from 'auth'" -a 'whoami' -d 'auth whoami'
complete -c fulcrum -n "__fish_seen_subcommand_from 'auth'" -l json -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'automations' -d 'fulcrum automations'
complete -c fulcrum -n "__fish_seen_subcommand_from 'automations'" -a 'create' -d 'automations create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'automations'" -a 'delete' -d 'automations delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'automations'" -a 'list' -d 'automations list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'automations'" -a 'templates' -d 'automations templates'
complete -c fulcrum -n "__fish_seen_subcommand_from 'automations'" -a 'update' -d 'automations update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'automations'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'automations'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'automations')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'backup' -d 'fulcrum backup'
complete -c fulcrum -n "__fish_seen_subcommand_from 'backup'" -a 'create' -d 'backup create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'backup'" -a 'restore' -d 'backup restore'
complete -c fulcrum -n "__fish_seen_subcommand_from 'backup'" -l json -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'comments' -d 'fulcrum comments'
complete -c fulcrum -n "__fish_seen_subcommand_from 'comments'" -a 'add-reaction' -d 'comments add-reaction'
complete -c fulcrum -n "__fish_seen_subcommand_from 'comments'" -a 'create' -d 'comments create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'comments'" -a 'delete' -d 'comments delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'comments'" -a 'list' -d 'comments list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'comments'" -a 'remove-reaction' -d 'comments remove-reaction'
complete -c fulcrum -n "__fish_seen_subcommand_from 'comments'" -a 'resolve' -d 'comments resolve'
complete -c fulcrum -n "__fish_seen_subcommand_from 'comments'" -a 'subscribe' -d 'comments subscribe'
complete -c fulcrum -n "__fish_seen_subcommand_from 'comments'" -a 'threaded' -d 'comments threaded'
complete -c fulcrum -n "__fish_seen_subcommand_from 'comments'" -a 'unresolve' -d 'comments unresolve'
complete -c fulcrum -n "__fish_seen_subcommand_from 'comments'" -a 'unsubscribe' -d 'comments unsubscribe'
complete -c fulcrum -n "__fish_seen_subcommand_from 'comments'" -a 'watchers' -d 'comments watchers'
complete -c fulcrum -n "__fish_seen_subcommand_from 'comments'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'comments'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'comments')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'connectors' -d 'fulcrum connectors'
complete -c fulcrum -n "__fish_seen_subcommand_from 'connectors'" -a 'disable' -d 'connectors disable'
complete -c fulcrum -n "__fish_seen_subcommand_from 'connectors'" -a 'enable' -d 'connectors enable'
complete -c fulcrum -n "__fish_seen_subcommand_from 'connectors'" -a 'get' -d 'connectors get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'connectors'" -a 'list' -d 'connectors list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'connectors'" -a 'runs get' -d 'connectors runs get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'connectors'" -a 'runs list' -d 'connectors runs list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'connectors'" -a 'sync' -d 'connectors sync'
complete -c fulcrum -n "__fish_seen_subcommand_from 'connectors'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'connectors'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'connectors')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'context' -d 'fulcrum context'
complete -c fulcrum -n "__fish_seen_subcommand_from 'context'" -a 'assemble' -d 'context assemble'
complete -c fulcrum -n "__fish_seen_subcommand_from 'context'" -a 'preview' -d 'context preview'
complete -c fulcrum -n "__fish_seen_subcommand_from 'context'" -l json -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'credentials' -d 'fulcrum credentials'
complete -c fulcrum -n "__fish_seen_subcommand_from 'credentials'" -a 'archive' -d 'credentials archive'
complete -c fulcrum -n "__fish_seen_subcommand_from 'credentials'" -a 'get' -d 'credentials get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'credentials'" -a 'list' -d 'credentials list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'credentials'" -a 'remove' -d 'credentials remove'
complete -c fulcrum -n "__fish_seen_subcommand_from 'credentials'" -a 'rotate' -d 'credentials rotate'
complete -c fulcrum -n "__fish_seen_subcommand_from 'credentials'" -a 'set' -d 'credentials set'
complete -c fulcrum -n "__fish_seen_subcommand_from 'credentials'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'credentials'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'credentials')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'custom_fields' -d 'fulcrum custom_fields'
complete -c fulcrum -n "__fish_seen_subcommand_from 'custom_fields'" -a 'create' -d 'custom_fields create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'custom_fields'" -a 'delete' -d 'custom_fields delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'custom_fields'" -a 'list' -d 'custom_fields list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'custom_fields'" -a 'reorder' -d 'custom_fields reorder'
complete -c fulcrum -n "__fish_seen_subcommand_from 'custom_fields'" -a 'update' -d 'custom_fields update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'custom_fields'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'custom_fields'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'custom_fields')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'customFieldDefs' -d 'fulcrum customFieldDefs'
complete -c fulcrum -n "__fish_seen_subcommand_from 'customFieldDefs'" -a 'list' -d 'customFieldDefs list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'customFieldDefs'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'customFieldDefs'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'customFieldDefs')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'dataExport' -d 'fulcrum dataExport'
complete -c fulcrum -n "__fish_seen_subcommand_from 'dataExport'" -a 'create' -d 'dataExport create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'dataExport'" -l json -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'dataImport' -d 'fulcrum dataImport'
complete -c fulcrum -n "__fish_seen_subcommand_from 'dataImport'" -a 'preflight' -d 'dataImport preflight'
complete -c fulcrum -n "__fish_seen_subcommand_from 'dataImport'" -a 'run' -d 'dataImport run'
complete -c fulcrum -n "__fish_seen_subcommand_from 'dataImport'" -l json -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'db' -d 'fulcrum db'
complete -c fulcrum -n "__fish_seen_subcommand_from 'db'" -a 'ping' -d 'db ping'
complete -c fulcrum -n "__fish_seen_subcommand_from 'db'" -l json -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'doc_comments' -d 'fulcrum doc_comments'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_comments'" -a 'create' -d 'doc_comments create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_comments'" -a 'delete' -d 'doc_comments delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_comments'" -a 'list' -d 'doc_comments list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_comments'" -a 'resolve' -d 'doc_comments resolve'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_comments'" -a 'update' -d 'doc_comments update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_comments'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_comments'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'doc_comments')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'doc_links' -d 'fulcrum doc_links'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_links'" -a 'create' -d 'doc_links create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_links'" -a 'delete' -d 'doc_links delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_links'" -a 'list' -d 'doc_links list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_links'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_links'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'doc_links')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'doc_versions' -d 'fulcrum doc_versions'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_versions'" -a 'diff' -d 'doc_versions diff'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_versions'" -a 'get' -d 'doc_versions get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_versions'" -a 'list' -d 'doc_versions list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_versions'" -a 'restore' -d 'doc_versions restore'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_versions'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'doc_versions'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'doc_versions')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'docs' -d 'fulcrum docs'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'comments create' -d 'docs comments create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'comments delete' -d 'docs comments delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'comments list' -d 'docs comments list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'comments resolve' -d 'docs comments resolve'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'comments update' -d 'docs comments update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'create' -d 'docs create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'delete' -d 'docs delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'get' -d 'docs get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'links list-backlinks' -d 'docs links list-backlinks'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'links list-forward-links' -d 'docs links list-forward-links'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'list' -d 'docs list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'templates list' -d 'docs templates list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'templates resolve' -d 'docs templates resolve'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'update' -d 'docs update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'versions diff' -d 'docs versions diff'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'versions get' -d 'docs versions get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'versions list' -d 'docs versions list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -a 'versions restore' -d 'docs versions restore'
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'docs'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'docs')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'doctor' -d 'fulcrum doctor'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doctor'" -a 'run' -d 'doctor run'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doctor'" -a 'subsystems' -d 'doctor subsystems'
complete -c fulcrum -n "__fish_seen_subcommand_from 'doctor'" -l json -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'errorLogs' -d 'fulcrum errorLogs'
complete -c fulcrum -n "__fish_seen_subcommand_from 'errorLogs'" -a 'clear' -d 'errorLogs clear'
complete -c fulcrum -n "__fish_seen_subcommand_from 'errorLogs'" -a 'get' -d 'errorLogs get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'errorLogs'" -a 'list' -d 'errorLogs list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'errorLogs'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'errorLogs'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'errorLogs')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'flags' -d 'fulcrum flags'
complete -c fulcrum -n "__fish_seen_subcommand_from 'flags'" -a 'evaluate' -d 'flags evaluate'
complete -c fulcrum -n "__fish_seen_subcommand_from 'flags'" -a 'experiments assignments' -d 'flags experiments assignments'
complete -c fulcrum -n "__fish_seen_subcommand_from 'flags'" -a 'experiments create' -d 'flags experiments create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'flags'" -a 'experiments list' -d 'flags experiments list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'flags'" -a 'experiments metrics' -d 'flags experiments metrics'
complete -c fulcrum -n "__fish_seen_subcommand_from 'flags'" -a 'list' -d 'flags list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'flags'" -a 'set' -d 'flags set'
complete -c fulcrum -n "__fish_seen_subcommand_from 'flags'" -a 'set-override' -d 'flags set-override'
complete -c fulcrum -n "__fish_seen_subcommand_from 'flags'" -a 'set-rollout' -d 'flags set-rollout'
complete -c fulcrum -n "__fish_seen_subcommand_from 'flags'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'flags'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'flags')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'fulcrum_skills' -d 'fulcrum fulcrum_skills'
complete -c fulcrum -n "__fish_seen_subcommand_from 'fulcrum_skills'" -a 'conflicts list' -d 'fulcrum_skills conflicts list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'fulcrum_skills'" -a 'conflicts override' -d 'fulcrum_skills conflicts override'
complete -c fulcrum -n "__fish_seen_subcommand_from 'fulcrum_skills'" -a 'install' -d 'fulcrum_skills install'
complete -c fulcrum -n "__fish_seen_subcommand_from 'fulcrum_skills'" -a 'list' -d 'fulcrum_skills list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'fulcrum_skills'" -a 'lock override' -d 'fulcrum_skills lock override'
complete -c fulcrum -n "__fish_seen_subcommand_from 'fulcrum_skills'" -a 'registry list' -d 'fulcrum_skills registry list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'fulcrum_skills'" -a 'resolve-conflict' -d 'fulcrum_skills resolve-conflict'
complete -c fulcrum -n "__fish_seen_subcommand_from 'fulcrum_skills'" -a 'sync' -d 'fulcrum_skills sync'
complete -c fulcrum -n "__fish_seen_subcommand_from 'fulcrum_skills'" -a 'uninstall' -d 'fulcrum_skills uninstall'
complete -c fulcrum -n "__fish_seen_subcommand_from 'fulcrum_skills'" -a 'upgrade' -d 'fulcrum_skills upgrade'
complete -c fulcrum -n "__fish_seen_subcommand_from 'fulcrum_skills'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'fulcrum_skills'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'fulcrum_skills')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'health' -d 'fulcrum health'
complete -c fulcrum -n "__fish_seen_subcommand_from 'health'" -a 'ping' -d 'health ping'
complete -c fulcrum -n "__fish_seen_subcommand_from 'health'" -l json -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'inference' -d 'fulcrum inference'
complete -c fulcrum -n "__fish_seen_subcommand_from 'inference'" -a 'backends list' -d 'inference backends list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'inference'" -a 'backends probe' -d 'inference backends probe'
complete -c fulcrum -n "__fish_seen_subcommand_from 'inference'" -a 'classify' -d 'inference classify'
complete -c fulcrum -n "__fish_seen_subcommand_from 'inference'" -a 'config get' -d 'inference config get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'inference'" -a 'config set' -d 'inference config set'
complete -c fulcrum -n "__fish_seen_subcommand_from 'inference'" -a 'embed' -d 'inference embed'
complete -c fulcrum -n "__fish_seen_subcommand_from 'inference'" -a 'generate' -d 'inference generate'
complete -c fulcrum -n "__fish_seen_subcommand_from 'inference'" -a 'health' -d 'inference health'
complete -c fulcrum -n "__fish_seen_subcommand_from 'inference'" -a 'models list' -d 'inference models list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'inference'" -a 'models pull' -d 'inference models pull'
complete -c fulcrum -n "__fish_seen_subcommand_from 'inference'" -a 'models rm' -d 'inference models rm'
complete -c fulcrum -n "__fish_seen_subcommand_from 'inference'" -a 'provider set' -d 'inference provider set'
complete -c fulcrum -n "__fish_seen_subcommand_from 'inference'" -a 'provider test' -d 'inference provider test'
complete -c fulcrum -n "__fish_seen_subcommand_from 'inference'" -a 'tokenize' -d 'inference tokenize'
complete -c fulcrum -n "__fish_seen_subcommand_from 'inference'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'inference'" -l watch -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'invitations' -d 'fulcrum invitations'
complete -c fulcrum -n "__fish_seen_subcommand_from 'invitations'" -a 'create' -d 'invitations create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'invitations'" -a 'get' -d 'invitations get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'invitations'" -a 'list' -d 'invitations list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'invitations'" -a 'revoke' -d 'invitations revoke'
complete -c fulcrum -n "__fish_seen_subcommand_from 'invitations'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'invitations'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'invitations')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'memories' -d 'fulcrum memories'
complete -c fulcrum -n "__fish_seen_subcommand_from 'memories'" -a 'create' -d 'memories create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'memories'" -a 'delete' -d 'memories delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'memories'" -a 'get' -d 'memories get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'memories'" -a 'list' -d 'memories list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'memories'" -a 'search' -d 'memories search'
complete -c fulcrum -n "__fish_seen_subcommand_from 'memories'" -a 'update' -d 'memories update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'memories'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'memories'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'memories')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'notify' -d 'fulcrum notify'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -a 'channels config' -d 'notify channels config'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -a 'channels list' -d 'notify channels list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -a 'channels test' -d 'notify channels test'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -a 'list' -d 'notify list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -a 'mark-all-read' -d 'notify mark-all-read'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -a 'mark-read' -d 'notify mark-read'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -a 'mute' -d 'notify mute'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -a 'mutes list' -d 'notify mutes list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -a 'quiet-hours get' -d 'notify quiet-hours get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -a 'quiet-hours set' -d 'notify quiet-hours set'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -a 'rules create' -d 'notify rules create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -a 'rules delete' -d 'notify rules delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -a 'rules get' -d 'notify rules get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -a 'rules list' -d 'notify rules list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -a 'rules update' -d 'notify rules update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -a 'unmute' -d 'notify unmute'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -a 'unread-count' -d 'notify unread-count'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'notify'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'notify')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'notifySubscriptions' -d 'fulcrum notifySubscriptions'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notifySubscriptions'" -a 'on-new-notification' -d 'notifySubscriptions on-new-notification'
complete -c fulcrum -n "__fish_seen_subcommand_from 'notifySubscriptions'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'notifySubscriptions'" -l watch -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'orchestrationSubscriptions' -d 'fulcrum orchestrationSubscriptions'
complete -c fulcrum -n "__fish_seen_subcommand_from 'orchestrationSubscriptions'" -a 'on-state-change' -d 'orchestrationSubscriptions on-state-change'
complete -c fulcrum -n "__fish_seen_subcommand_from 'orchestrationSubscriptions'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'orchestrationSubscriptions'" -l watch -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'orgs' -d 'fulcrum orgs'
complete -c fulcrum -n "__fish_seen_subcommand_from 'orgs'" -a 'get' -d 'orgs get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'orgs'" -a 'members list' -d 'orgs members list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'orgs'" -a 'members remove' -d 'orgs members remove'
complete -c fulcrum -n "__fish_seen_subcommand_from 'orgs'" -a 'members update-role' -d 'orgs members update-role'
complete -c fulcrum -n "__fish_seen_subcommand_from 'orgs'" -a 'update' -d 'orgs update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'orgs'" -l json -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'projects' -d 'fulcrum projects'
complete -c fulcrum -n "__fish_seen_subcommand_from 'projects'" -a 'create' -d 'projects create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'projects'" -a 'delete' -d 'projects delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'projects'" -a 'get' -d 'projects get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'projects'" -a 'list' -d 'projects list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'projects'" -a 'stats' -d 'projects stats'
complete -c fulcrum -n "__fish_seen_subcommand_from 'projects'" -a 'update' -d 'projects update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'projects'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'projects'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'projects')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'recurrence' -d 'fulcrum recurrence'
complete -c fulcrum -n "__fish_seen_subcommand_from 'recurrence'" -a 'create' -d 'recurrence create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'recurrence'" -a 'delete' -d 'recurrence delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'recurrence'" -a 'list' -d 'recurrence list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'recurrence'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'recurrence'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'recurrence')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'relationships' -d 'fulcrum relationships'
complete -c fulcrum -n "__fish_seen_subcommand_from 'relationships'" -a 'blocked-items' -d 'relationships blocked-items'
complete -c fulcrum -n "__fish_seen_subcommand_from 'relationships'" -a 'blockers' -d 'relationships blockers'
complete -c fulcrum -n "__fish_seen_subcommand_from 'relationships'" -a 'create' -d 'relationships create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'relationships'" -a 'delete' -d 'relationships delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'relationships'" -a 'list-blocked-by' -d 'relationships list-blocked-by'
complete -c fulcrum -n "__fish_seen_subcommand_from 'relationships'" -a 'list-for-task' -d 'relationships list-for-task'
complete -c fulcrum -n "__fish_seen_subcommand_from 'relationships'" -a 'mark-as-duplicate' -d 'relationships mark-as-duplicate'
complete -c fulcrum -n "__fish_seen_subcommand_from 'relationships'" -a 'summary' -d 'relationships summary'
complete -c fulcrum -n "__fish_seen_subcommand_from 'relationships'" -l json -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'repo_branches' -d 'fulcrum repo_branches'
complete -c fulcrum -n "__fish_seen_subcommand_from 'repo_branches'" -a 'get' -d 'repo_branches get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'repo_branches'" -a 'list' -d 'repo_branches list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'repo_branches'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'repo_branches'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'repo_branches')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'repo_commits' -d 'fulcrum repo_commits'
complete -c fulcrum -n "__fish_seen_subcommand_from 'repo_commits'" -a 'get' -d 'repo_commits get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'repo_commits'" -a 'list' -d 'repo_commits list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'repo_commits'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'repo_commits'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'repo_commits')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'reports' -d 'fulcrum reports'
complete -c fulcrum -n "__fish_seen_subcommand_from 'reports'" -a 'burndown' -d 'reports burndown'
complete -c fulcrum -n "__fish_seen_subcommand_from 'reports'" -l json -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'repos' -d 'fulcrum repos'
complete -c fulcrum -n "__fish_seen_subcommand_from 'repos'" -a 'get' -d 'repos get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'repos'" -a 'list' -d 'repos list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'repos'" -a 'register' -d 'repos register'
complete -c fulcrum -n "__fish_seen_subcommand_from 'repos'" -a 'status-repo' -d 'repos status-repo'
complete -c fulcrum -n "__fish_seen_subcommand_from 'repos'" -a 'sync' -d 'repos sync'
complete -c fulcrum -n "__fish_seen_subcommand_from 'repos'" -a 'sync-repo' -d 'repos sync-repo'
complete -c fulcrum -n "__fish_seen_subcommand_from 'repos'" -a 'unregister' -d 'repos unregister'
complete -c fulcrum -n "__fish_seen_subcommand_from 'repos'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'repos'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'repos')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'routing' -d 'fulcrum routing'
complete -c fulcrum -n "__fish_seen_subcommand_from 'routing'" -a 'config update-llm-gate' -d 'routing config update-llm-gate'
complete -c fulcrum -n "__fish_seen_subcommand_from 'routing'" -a 'create' -d 'routing create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'routing'" -a 'delete' -d 'routing delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'routing'" -a 'drafts approve' -d 'routing drafts approve'
complete -c fulcrum -n "__fish_seen_subcommand_from 'routing'" -a 'drafts delete' -d 'routing drafts delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'routing'" -a 'drafts list' -d 'routing drafts list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'routing'" -a 'drafts update' -d 'routing drafts update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'routing'" -a 'dry-run' -d 'routing dry-run'
complete -c fulcrum -n "__fish_seen_subcommand_from 'routing'" -a 'get' -d 'routing get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'routing'" -a 'list' -d 'routing list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'routing'" -a 'test' -d 'routing test'
complete -c fulcrum -n "__fish_seen_subcommand_from 'routing'" -a 'update' -d 'routing update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'routing'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'routing'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'routing')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'runsSubscriptions' -d 'fulcrum runsSubscriptions'
complete -c fulcrum -n "__fish_seen_subcommand_from 'runsSubscriptions'" -a 'on-run-update' -d 'runsSubscriptions on-run-update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'runsSubscriptions'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'runsSubscriptions'" -l watch -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'saved_views' -d 'fulcrum saved_views'
complete -c fulcrum -n "__fish_seen_subcommand_from 'saved_views'" -a 'create' -d 'saved_views create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'saved_views'" -a 'delete' -d 'saved_views delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'saved_views'" -a 'get' -d 'saved_views get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'saved_views'" -a 'list' -d 'saved_views list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'saved_views'" -a 'update' -d 'saved_views update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'saved_views'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'saved_views'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'saved_views')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'search' -d 'fulcrum search'
complete -c fulcrum -n "__fish_seen_subcommand_from 'search'" -a 'query' -d 'search query'
complete -c fulcrum -n "__fish_seen_subcommand_from 'search'" -a 'record-click' -d 'search record-click'
complete -c fulcrum -n "__fish_seen_subcommand_from 'search'" -a 'saved-create' -d 'search saved-create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'search'" -a 'saved-delete' -d 'search saved-delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'search'" -a 'saved-list' -d 'search saved-list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'search'" -a 'saved-update' -d 'search saved-update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'search'" -a 'snapshot' -d 'search snapshot'
complete -c fulcrum -n "__fish_seen_subcommand_from 'search'" -a 'suggest' -d 'search suggest'
complete -c fulcrum -n "__fish_seen_subcommand_from 'search'" -l json -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'sprints' -d 'fulcrum sprints'
complete -c fulcrum -n "__fish_seen_subcommand_from 'sprints'" -a 'add-task' -d 'sprints add-task'
complete -c fulcrum -n "__fish_seen_subcommand_from 'sprints'" -a 'close' -d 'sprints close'
complete -c fulcrum -n "__fish_seen_subcommand_from 'sprints'" -a 'create' -d 'sprints create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'sprints'" -a 'delete' -d 'sprints delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'sprints'" -a 'get' -d 'sprints get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'sprints'" -a 'list' -d 'sprints list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'sprints'" -a 'remove-task' -d 'sprints remove-task'
complete -c fulcrum -n "__fish_seen_subcommand_from 'sprints'" -a 'start' -d 'sprints start'
complete -c fulcrum -n "__fish_seen_subcommand_from 'sprints'" -a 'update' -d 'sprints update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'sprints'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'sprints'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'sprints')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'taskCustomFields' -d 'fulcrum taskCustomFields'
complete -c fulcrum -n "__fish_seen_subcommand_from 'taskCustomFields'" -a 'clear' -d 'taskCustomFields clear'
complete -c fulcrum -n "__fish_seen_subcommand_from 'taskCustomFields'" -a 'set' -d 'taskCustomFields set'
complete -c fulcrum -n "__fish_seen_subcommand_from 'taskCustomFields'" -l json -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'tasks' -d 'fulcrum tasks'
complete -c fulcrum -n "__fish_seen_subcommand_from 'tasks'" -a 'bulk-delete' -d 'tasks bulk-delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'tasks'" -a 'bulk-update' -d 'tasks bulk-update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'tasks'" -a 'create' -d 'tasks create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'tasks'" -a 'delete' -d 'tasks delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'tasks'" -a 'get' -d 'tasks get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'tasks'" -a 'list' -d 'tasks list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'tasks'" -a 'list-children' -d 'tasks list-children'
complete -c fulcrum -n "__fish_seen_subcommand_from 'tasks'" -a 'set-dependencies' -d 'tasks set-dependencies'
complete -c fulcrum -n "__fish_seen_subcommand_from 'tasks'" -a 'set-parent' -d 'tasks set-parent'
complete -c fulcrum -n "__fish_seen_subcommand_from 'tasks'" -a 'update' -d 'tasks update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'tasks'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'tasks'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'tasks')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'telemetry' -d 'fulcrum telemetry'
complete -c fulcrum -n "__fish_seen_subcommand_from 'telemetry'" -a 'opt-in' -d 'telemetry opt-in'
complete -c fulcrum -n "__fish_seen_subcommand_from 'telemetry'" -a 'opt-out' -d 'telemetry opt-out'
complete -c fulcrum -n "__fish_seen_subcommand_from 'telemetry'" -a 'purge' -d 'telemetry purge'
complete -c fulcrum -n "__fish_seen_subcommand_from 'telemetry'" -a 'status' -d 'telemetry status'
complete -c fulcrum -n "__fish_seen_subcommand_from 'telemetry'" -l json -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'templates' -d 'fulcrum templates'
complete -c fulcrum -n "__fish_seen_subcommand_from 'templates'" -a 'apply-template' -d 'templates apply-template'
complete -c fulcrum -n "__fish_seen_subcommand_from 'templates'" -a 'create' -d 'templates create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'templates'" -a 'delete' -d 'templates delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'templates'" -a 'list' -d 'templates list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'templates'" -a 'set-default' -d 'templates set-default'
complete -c fulcrum -n "__fish_seen_subcommand_from 'templates'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'templates'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'templates')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'theme' -d 'fulcrum theme'
complete -c fulcrum -n "__fish_seen_subcommand_from 'theme'" -a 'get' -d 'theme get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'theme'" -a 'get-theme' -d 'theme get-theme'
complete -c fulcrum -n "__fish_seen_subcommand_from 'theme'" -a 'list-themes' -d 'theme list-themes'
complete -c fulcrum -n "__fish_seen_subcommand_from 'theme'" -a 'set-theme' -d 'theme set-theme'
complete -c fulcrum -n "__fish_seen_subcommand_from 'theme'" -a 'update' -d 'theme update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'theme'" -l json -d option
complete -c fulcrum -n "__fish_use_subcommand" -a 'webhooks' -d 'fulcrum webhooks'
complete -c fulcrum -n "__fish_seen_subcommand_from 'webhooks'" -a 'create' -d 'webhooks create'
complete -c fulcrum -n "__fish_seen_subcommand_from 'webhooks'" -a 'delete' -d 'webhooks delete'
complete -c fulcrum -n "__fish_seen_subcommand_from 'webhooks'" -a 'deliveries get' -d 'webhooks deliveries get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'webhooks'" -a 'deliveries list' -d 'webhooks deliveries list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'webhooks'" -a 'get' -d 'webhooks get'
complete -c fulcrum -n "__fish_seen_subcommand_from 'webhooks'" -a 'list' -d 'webhooks list'
complete -c fulcrum -n "__fish_seen_subcommand_from 'webhooks'" -a 'update' -d 'webhooks update'
complete -c fulcrum -n "__fish_seen_subcommand_from 'webhooks'" -l json -d option
complete -c fulcrum -n "__fish_seen_subcommand_from 'webhooks'; and __fish_prev_arg_in get delete update" -a "(__fulcrum_dynamic_ids 'webhooks')"
complete -c fulcrum -n "__fish_use_subcommand" -a 'workflows' -d 'fulcrum workflows'
complete -c fulcrum -n "__fish_seen_subcommand_from 'workflows'" -a 'get-default' -d 'workflows get-default'
complete -c fulcrum -n "__fish_seen_subcommand_from 'workflows'" -a 'get-enabled-task-types' -d 'workflows get-enabled-task-types'
complete -c fulcrum -n "__fish_seen_subcommand_from 'workflows'" -a 'get-methodology' -d 'workflows get-methodology'
complete -c fulcrum -n "__fish_seen_subcommand_from 'workflows'" -a 'get-transitions' -d 'workflows get-transitions'
complete -c fulcrum -n "__fish_seen_subcommand_from 'workflows'" -a 'update-enabled-task-types' -d 'workflows update-enabled-task-types'
complete -c fulcrum -n "__fish_seen_subcommand_from 'workflows'" -a 'update-methodology' -d 'workflows update-methodology'
complete -c fulcrum -n "__fish_seen_subcommand_from 'workflows'" -a 'update-transitions' -d 'workflows update-transitions'
complete -c fulcrum -n "__fish_seen_subcommand_from 'workflows'" -a 'validate-transition' -d 'workflows validate-transition'
complete -c fulcrum -n "__fish_seen_subcommand_from 'workflows'" -l json -d option
