#compdef fulcrum
# zsh completion for fulcrum
# Generated by scripts/cli/codegen.ts.
_fulcrum_dynamic_ids() {
  command fulcrum "$1" list --json 2>/dev/null | jq -r '.[]?.id // empty' 2>/dev/null || true
}

_fulcrum() {
  local -a domains
  domains=('agent_runs:fulcrum agent_runs' 'agents:fulcrum agents' 'artifacts:fulcrum artifacts' 'audit:fulcrum audit' 'auth:fulcrum auth' 'automations:fulcrum automations' 'backup:fulcrum backup' 'comments:fulcrum comments' 'connectors:fulcrum connectors' 'context:fulcrum context' 'credentials:fulcrum credentials' 'custom_fields:fulcrum custom_fields' 'customFieldDefs:fulcrum customFieldDefs' 'dataExport:fulcrum dataExport' 'dataImport:fulcrum dataImport' 'db:fulcrum db' 'doc_comments:fulcrum doc_comments' 'doc_links:fulcrum doc_links' 'doc_versions:fulcrum doc_versions' 'docs:fulcrum docs' 'doctor:fulcrum doctor' 'errorLogs:fulcrum errorLogs' 'flags:fulcrum flags' 'fulcrum_skills:fulcrum fulcrum_skills' 'health:fulcrum health' 'inference:fulcrum inference' 'invitations:fulcrum invitations' 'memories:fulcrum memories' 'notify:fulcrum notify' 'notifySubscriptions:fulcrum notifySubscriptions' 'orchestrationSubscriptions:fulcrum orchestrationSubscriptions' 'orgs:fulcrum orgs' 'projects:fulcrum projects' 'recurrence:fulcrum recurrence' 'relationships:fulcrum relationships' 'repo_branches:fulcrum repo_branches' 'repo_commits:fulcrum repo_commits' 'reports:fulcrum reports' 'repos:fulcrum repos' 'routing:fulcrum routing' 'runsSubscriptions:fulcrum runsSubscriptions' 'saved_views:fulcrum saved_views' 'search:fulcrum search' 'sprints:fulcrum sprints' 'taskCustomFields:fulcrum taskCustomFields' 'tasks:fulcrum tasks' 'telemetry:fulcrum telemetry' 'templates:fulcrum templates' 'theme:fulcrum theme' 'webhooks:fulcrum webhooks' 'workflows:fulcrum workflows')
  if (( CURRENT == 2 )); then
    _describe 'fulcrum command' domains
    return
  fi
  case $words[2] in
    agent_runs)
      local -a values=('cancel:fulcrum agent_runs cancel' 'create:fulcrum agent_runs create' 'get:fulcrum agent_runs get' 'list:fulcrum agent_runs list' 'retry:fulcrum agent_runs retry' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'agent_runs')
        return
      fi
      _describe 'command or option' values
      ;;
    agents)
      local -a values=('get-profile:fulcrum agents get-profile' 'list-profiles:fulcrum agents list-profiles' 'test-profile:fulcrum agents test-profile' '--json:option')
      _describe 'command or option' values
      ;;
    artifacts)
      local -a values=('archive:fulcrum artifacts archive' 'delete:fulcrum artifacts delete' 'download:fulcrum artifacts download' 'get:fulcrum artifacts get' 'list:fulcrum artifacts list' 'unarchive:fulcrum artifacts unarchive' 'upload:fulcrum artifacts upload' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'artifacts')
        return
      fi
      _describe 'command or option' values
      ;;
    audit)
      local -a values=('export:fulcrum audit export' 'query:fulcrum audit query' 'retention-policy get:fulcrum audit retention-policy get' 'retention-policy list:fulcrum audit retention-policy list' 'retention-policy set:fulcrum audit retention-policy set' '--json:option')
      _describe 'command or option' values
      ;;
    auth)
      local -a values=('accept-invite:fulcrum auth accept-invite' 'invite:fulcrum auth invite' 'whoami:fulcrum auth whoami' '--json:option')
      _describe 'command or option' values
      ;;
    automations)
      local -a values=('create:fulcrum automations create' 'delete:fulcrum automations delete' 'list:fulcrum automations list' 'templates:fulcrum automations templates' 'update:fulcrum automations update' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'automations')
        return
      fi
      _describe 'command or option' values
      ;;
    backup)
      local -a values=('create:fulcrum backup create' 'restore:fulcrum backup restore' '--json:option')
      _describe 'command or option' values
      ;;
    comments)
      local -a values=('add-reaction:fulcrum comments add-reaction' 'create:fulcrum comments create' 'delete:fulcrum comments delete' 'list:fulcrum comments list' 'remove-reaction:fulcrum comments remove-reaction' 'resolve:fulcrum comments resolve' 'subscribe:fulcrum comments subscribe' 'threaded:fulcrum comments threaded' 'unresolve:fulcrum comments unresolve' 'unsubscribe:fulcrum comments unsubscribe' 'watchers:fulcrum comments watchers' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'comments')
        return
      fi
      _describe 'command or option' values
      ;;
    connectors)
      local -a values=('disable:fulcrum connectors disable' 'enable:fulcrum connectors enable' 'get:fulcrum connectors get' 'list:fulcrum connectors list' 'runs get:fulcrum connectors runs get' 'runs list:fulcrum connectors runs list' 'sync:fulcrum connectors sync' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'connectors')
        return
      fi
      _describe 'command or option' values
      ;;
    context)
      local -a values=('assemble:fulcrum context assemble' 'preview:fulcrum context preview' '--json:option')
      _describe 'command or option' values
      ;;
    credentials)
      local -a values=('archive:fulcrum credentials archive' 'get:fulcrum credentials get' 'list:fulcrum credentials list' 'remove:fulcrum credentials remove' 'rotate:fulcrum credentials rotate' 'set:fulcrum credentials set' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'credentials')
        return
      fi
      _describe 'command or option' values
      ;;
    custom_fields)
      local -a values=('create:fulcrum custom_fields create' 'delete:fulcrum custom_fields delete' 'list:fulcrum custom_fields list' 'reorder:fulcrum custom_fields reorder' 'update:fulcrum custom_fields update' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'custom_fields')
        return
      fi
      _describe 'command or option' values
      ;;
    customFieldDefs)
      local -a values=('list:fulcrum customFieldDefs list' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'customFieldDefs')
        return
      fi
      _describe 'command or option' values
      ;;
    dataExport)
      local -a values=('create:fulcrum dataExport create' '--json:option')
      _describe 'command or option' values
      ;;
    dataImport)
      local -a values=('preflight:fulcrum dataImport preflight' 'run:fulcrum dataImport run' '--json:option')
      _describe 'command or option' values
      ;;
    db)
      local -a values=('ping:fulcrum db ping' '--json:option')
      _describe 'command or option' values
      ;;
    doc_comments)
      local -a values=('create:fulcrum doc_comments create' 'delete:fulcrum doc_comments delete' 'list:fulcrum doc_comments list' 'resolve:fulcrum doc_comments resolve' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'doc_comments')
        return
      fi
      _describe 'command or option' values
      ;;
    doc_links)
      local -a values=('create:fulcrum doc_links create' 'delete:fulcrum doc_links delete' 'list:fulcrum doc_links list' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'doc_links')
        return
      fi
      _describe 'command or option' values
      ;;
    doc_versions)
      local -a values=('diff:fulcrum doc_versions diff' 'list:fulcrum doc_versions list' 'restore:fulcrum doc_versions restore' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'doc_versions')
        return
      fi
      _describe 'command or option' values
      ;;
    docs)
      local -a values=('comments create:fulcrum docs comments create' 'comments delete:fulcrum docs comments delete' 'comments list:fulcrum docs comments list' 'comments resolve:fulcrum docs comments resolve' 'comments update:fulcrum docs comments update' 'create:fulcrum docs create' 'delete:fulcrum docs delete' 'get:fulcrum docs get' 'links list-backlinks:fulcrum docs links list-backlinks' 'links list-forward-links:fulcrum docs links list-forward-links' 'list:fulcrum docs list' 'templates list:fulcrum docs templates list' 'templates resolve:fulcrum docs templates resolve' 'update:fulcrum docs update' 'versions diff:fulcrum docs versions diff' 'versions get:fulcrum docs versions get' 'versions list:fulcrum docs versions list' 'versions restore:fulcrum docs versions restore' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'docs')
        return
      fi
      _describe 'command or option' values
      ;;
    doctor)
      local -a values=('run:fulcrum doctor run' 'subsystems:fulcrum doctor subsystems' '--json:option')
      _describe 'command or option' values
      ;;
    errorLogs)
      local -a values=('clear:fulcrum errorLogs clear' 'get:fulcrum errorLogs get' 'list:fulcrum errorLogs list' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'errorLogs')
        return
      fi
      _describe 'command or option' values
      ;;
    flags)
      local -a values=('evaluate:fulcrum flags evaluate' 'experiments assignments:fulcrum flags experiments assignments' 'experiments create:fulcrum flags experiments create' 'experiments list:fulcrum flags experiments list' 'experiments metrics:fulcrum flags experiments metrics' 'list:fulcrum flags list' 'set:fulcrum flags set' 'set-override:fulcrum flags set-override' 'set-rollout:fulcrum flags set-rollout' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'flags')
        return
      fi
      _describe 'command or option' values
      ;;
    fulcrum_skills)
      local -a values=('conflicts list:fulcrum fulcrum_skills conflicts list' 'conflicts override:fulcrum fulcrum_skills conflicts override' 'install:fulcrum fulcrum_skills install' 'list:fulcrum fulcrum_skills list' 'lock override:fulcrum fulcrum_skills lock override' 'registry list:fulcrum fulcrum_skills registry list' 'resolve-conflict:fulcrum fulcrum_skills resolve-conflict' 'sync:fulcrum fulcrum_skills sync' 'uninstall:fulcrum fulcrum_skills uninstall' 'upgrade:fulcrum fulcrum_skills upgrade' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'fulcrum_skills')
        return
      fi
      _describe 'command or option' values
      ;;
    health)
      local -a values=('ping:fulcrum health ping' '--json:option')
      _describe 'command or option' values
      ;;
    inference)
      local -a values=('backends list:fulcrum inference backends list' 'backends probe:fulcrum inference backends probe' 'classify:fulcrum inference classify' 'config get:fulcrum inference config get' 'config set:fulcrum inference config set' 'embed:fulcrum inference embed' 'generate:fulcrum inference generate' 'health:fulcrum inference health' 'models list:fulcrum inference models list' 'models pull:fulcrum inference models pull' 'models rm:fulcrum inference models rm' 'provider set:fulcrum inference provider set' 'provider test:fulcrum inference provider test' 'tokenize:fulcrum inference tokenize' '--json:option' '--watch:option')
      _describe 'command or option' values
      ;;
    invitations)
      local -a values=('create:fulcrum invitations create' 'get:fulcrum invitations get' 'list:fulcrum invitations list' 'revoke:fulcrum invitations revoke' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'invitations')
        return
      fi
      _describe 'command or option' values
      ;;
    memories)
      local -a values=('create:fulcrum memories create' 'delete:fulcrum memories delete' 'get:fulcrum memories get' 'list:fulcrum memories list' 'search:fulcrum memories search' 'update:fulcrum memories update' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'memories')
        return
      fi
      _describe 'command or option' values
      ;;
    notify)
      local -a values=('channels config:fulcrum notify channels config' 'channels list:fulcrum notify channels list' 'channels test:fulcrum notify channels test' 'list:fulcrum notify list' 'mark-all-read:fulcrum notify mark-all-read' 'mark-read:fulcrum notify mark-read' 'mute:fulcrum notify mute' 'mutes list:fulcrum notify mutes list' 'quiet-hours get:fulcrum notify quiet-hours get' 'quiet-hours set:fulcrum notify quiet-hours set' 'rules create:fulcrum notify rules create' 'rules delete:fulcrum notify rules delete' 'rules get:fulcrum notify rules get' 'rules list:fulcrum notify rules list' 'rules update:fulcrum notify rules update' 'unmute:fulcrum notify unmute' 'unread-count:fulcrum notify unread-count' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'notify')
        return
      fi
      _describe 'command or option' values
      ;;
    notifySubscriptions)
      local -a values=('on-new-notification:fulcrum notifySubscriptions on-new-notification' '--json:option' '--watch:option')
      _describe 'command or option' values
      ;;
    orchestrationSubscriptions)
      local -a values=('on-state-change:fulcrum orchestrationSubscriptions on-state-change' '--json:option' '--watch:option')
      _describe 'command or option' values
      ;;
    orgs)
      local -a values=('get:fulcrum orgs get' 'members list:fulcrum orgs members list' 'members remove:fulcrum orgs members remove' 'members update-role:fulcrum orgs members update-role' 'update:fulcrum orgs update' '--json:option')
      _describe 'command or option' values
      ;;
    projects)
      local -a values=('create:fulcrum projects create' 'delete:fulcrum projects delete' 'get:fulcrum projects get' 'list:fulcrum projects list' 'stats:fulcrum projects stats' 'update:fulcrum projects update' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'projects')
        return
      fi
      _describe 'command or option' values
      ;;
    recurrence)
      local -a values=('create:fulcrum recurrence create' 'delete:fulcrum recurrence delete' 'list:fulcrum recurrence list' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'recurrence')
        return
      fi
      _describe 'command or option' values
      ;;
    relationships)
      local -a values=('blocked-items:fulcrum relationships blocked-items' 'blockers:fulcrum relationships blockers' 'create:fulcrum relationships create' 'delete:fulcrum relationships delete' 'list-blocked-by:fulcrum relationships list-blocked-by' 'list-for-task:fulcrum relationships list-for-task' 'mark-as-duplicate:fulcrum relationships mark-as-duplicate' '--json:option')
      _describe 'command or option' values
      ;;
    repo_branches)
      local -a values=('get:fulcrum repo_branches get' 'list:fulcrum repo_branches list' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'repo_branches')
        return
      fi
      _describe 'command or option' values
      ;;
    repo_commits)
      local -a values=('get:fulcrum repo_commits get' 'list:fulcrum repo_commits list' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'repo_commits')
        return
      fi
      _describe 'command or option' values
      ;;
    reports)
      local -a values=('burndown:fulcrum reports burndown' '--json:option')
      _describe 'command or option' values
      ;;
    repos)
      local -a values=('get:fulcrum repos get' 'list:fulcrum repos list' 'register:fulcrum repos register' 'status-repo:fulcrum repos status-repo' 'sync:fulcrum repos sync' 'sync-repo:fulcrum repos sync-repo' 'unregister:fulcrum repos unregister' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'repos')
        return
      fi
      _describe 'command or option' values
      ;;
    routing)
      local -a values=('config update-llm-gate:fulcrum routing config update-llm-gate' 'create:fulcrum routing create' 'delete:fulcrum routing delete' 'drafts approve:fulcrum routing drafts approve' 'drafts delete:fulcrum routing drafts delete' 'drafts list:fulcrum routing drafts list' 'drafts update:fulcrum routing drafts update' 'dry-run:fulcrum routing dry-run' 'get:fulcrum routing get' 'list:fulcrum routing list' 'test:fulcrum routing test' 'update:fulcrum routing update' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'routing')
        return
      fi
      _describe 'command or option' values
      ;;
    runsSubscriptions)
      local -a values=('on-run-update:fulcrum runsSubscriptions on-run-update' '--json:option' '--watch:option')
      _describe 'command or option' values
      ;;
    saved_views)
      local -a values=('create:fulcrum saved_views create' 'delete:fulcrum saved_views delete' 'get:fulcrum saved_views get' 'list:fulcrum saved_views list' 'update:fulcrum saved_views update' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'saved_views')
        return
      fi
      _describe 'command or option' values
      ;;
    search)
      local -a values=('query:fulcrum search query' 'record-click:fulcrum search record-click' 'saved-create:fulcrum search saved-create' 'saved-delete:fulcrum search saved-delete' 'saved-list:fulcrum search saved-list' 'saved-update:fulcrum search saved-update' 'snapshot:fulcrum search snapshot' 'suggest:fulcrum search suggest' '--json:option')
      _describe 'command or option' values
      ;;
    sprints)
      local -a values=('add-task:fulcrum sprints add-task' 'close:fulcrum sprints close' 'create:fulcrum sprints create' 'delete:fulcrum sprints delete' 'get:fulcrum sprints get' 'list:fulcrum sprints list' 'remove-task:fulcrum sprints remove-task' 'start:fulcrum sprints start' 'update:fulcrum sprints update' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'sprints')
        return
      fi
      _describe 'command or option' values
      ;;
    taskCustomFields)
      local -a values=('clear:fulcrum taskCustomFields clear' 'set:fulcrum taskCustomFields set' '--json:option')
      _describe 'command or option' values
      ;;
    tasks)
      local -a values=('bulk-delete:fulcrum tasks bulk-delete' 'bulk-update:fulcrum tasks bulk-update' 'create:fulcrum tasks create' 'delete:fulcrum tasks delete' 'get:fulcrum tasks get' 'list:fulcrum tasks list' 'list-children:fulcrum tasks list-children' 'set-dependencies:fulcrum tasks set-dependencies' 'set-parent:fulcrum tasks set-parent' 'update:fulcrum tasks update' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'tasks')
        return
      fi
      _describe 'command or option' values
      ;;
    telemetry)
      local -a values=('opt-in:fulcrum telemetry opt-in' 'opt-out:fulcrum telemetry opt-out' 'purge:fulcrum telemetry purge' 'status:fulcrum telemetry status' '--json:option')
      _describe 'command or option' values
      ;;
    templates)
      local -a values=('apply-template:fulcrum templates apply-template' 'create:fulcrum templates create' 'delete:fulcrum templates delete' 'list:fulcrum templates list' 'set-default:fulcrum templates set-default' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'templates')
        return
      fi
      _describe 'command or option' values
      ;;
    theme)
      local -a values=('get-theme:fulcrum theme get-theme' 'list-themes:fulcrum theme list-themes' 'set-theme:fulcrum theme set-theme' '--json:option')
      _describe 'command or option' values
      ;;
    webhooks)
      local -a values=('create:fulcrum webhooks create' 'delete:fulcrum webhooks delete' 'deliveries get:fulcrum webhooks deliveries get' 'deliveries list:fulcrum webhooks deliveries list' 'get:fulcrum webhooks get' 'list:fulcrum webhooks list' 'update:fulcrum webhooks update' '--json:option')
      if [[ $words[CURRENT-1] == (get|delete|update) ]]; then
        _values 'ids' $(_fulcrum_dynamic_ids 'webhooks')
        return
      fi
      _describe 'command or option' values
      ;;
    workflows)
      local -a values=('get-default:fulcrum workflows get-default' 'get-enabled-task-types:fulcrum workflows get-enabled-task-types' 'get-methodology:fulcrum workflows get-methodology' 'get-transitions:fulcrum workflows get-transitions' 'update-enabled-task-types:fulcrum workflows update-enabled-task-types' 'update-methodology:fulcrum workflows update-methodology' 'update-transitions:fulcrum workflows update-transitions' 'validate-transition:fulcrum workflows validate-transition' '--json:option')
      _describe 'command or option' values
      ;;
  esac
}
_fulcrum "$@"
