#!/usr/bin/env bun

import { mkdir, readFile, readdir, realpath, stat, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";

export type LicenseClassification = "PASS" | "FAIL" | "UNKNOWN";

export interface LicensePackage {
  name: string;
  version: string;
  license: string;
  classification: LicenseClassification;
  source: string;
  packageRoot: string;
  path: string;
}

export interface LicenseAuditSummary {
  total: number;
  pass: number;
  fail: number;
  unknown: number;
}

export interface LicenseAuditResult {
  ok: boolean;
  generatedAt: string;
  rootDir: string;
  reportPath: string;
  summary: LicenseAuditSummary;
  packages: LicensePackage[];
  warnings: string[];
}

export interface LicenseAuditOptions {
  rootDir?: string;
  reportPath?: string;
}

const PASS_LICENSES = new Set([
  "MIT",
  "MIT-0",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "0BSD",
  "CC0",
  "CC0-1.0",
  "Unlicense",
  "CC-BY-4.0",
  "Python-2.0",
  "BlueOak-1.0.0",
]);

const FAIL_LICENSE_PATTERNS = [
  /\bAGPL\b/i,
  /\bGPL\b/i,
  /\bLGPL\b/i,
  /\bSSPL\b/i,
  /\bBSL\b/i,
  /\bBUSL\b/i,
  /\bcommercial\b/i,
  /\bproprietary\b/i,
  /\bCC-BY-NC\b/i,
];

const REPORT_FOOTER = "Web/TUI surfaces wired by Pillar 15/16 in Wave 5";

function licenseText(value: unknown): { license: string; source: string } {
  if (typeof value === "string" && value.trim()) {
    return { license: value.trim(), source: "license" };
  }

  if (value && typeof value === "object") {
    const record = value as Record<string, unknown>;
    if (typeof record["type"] === "string" && record["type"].trim()) {
      return { license: record["type"].trim(), source: "license.type" };
    }
  }

  return { license: "UNKNOWN", source: "missing" };
}

function legacyLicensesText(value: unknown): { license: string; source: string } | undefined {
  if (!Array.isArray(value) || value.length === 0) return undefined;

  const licenses = value
    .map((item) => {
      if (typeof item === "string") return item.trim();
      if (item && typeof item === "object") {
        const type = (item as Record<string, unknown>)["type"];
        if (typeof type === "string") return type.trim();
      }
      return "";
    })
    .filter(Boolean);

  if (licenses.length === 0) return undefined;
  return { license: licenses.join(" OR "), source: "licenses" };
}

function normalizeLicenseToken(token: string): string {
  return token
    .trim()
    .replace(/^\(+|\)+$/g, "")
    .replace(/^Apache 2\.0$/i, "Apache-2.0")
    .replace(/^BSD 2-Clause$/i, "BSD-2-Clause")
    .replace(/^BSD 3-Clause$/i, "BSD-3-Clause");
}

export function classifyLicense(license: string): LicenseClassification {
  if (license === "UNKNOWN") return "UNKNOWN";
  if (FAIL_LICENSE_PATTERNS.some((pattern) => pattern.test(license))) return "FAIL";

  const tokens = license
    .split(/\s+(?:OR|AND|WITH)\s+|[()]/i)
    .map(normalizeLicenseToken)
    .filter(Boolean);

  if (tokens.length > 0 && tokens.every((token) => PASS_LICENSES.has(token))) return "PASS";
  return "UNKNOWN";
}

function displayPath(rootDir: string, path: string): string {
  const rel = relative(rootDir, path);
  if (!rel || rel.startsWith("..")) return path;
  return rel;
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

function renderReport(result: LicenseAuditResult): string {
  const lines = [
    "# License Dependencies Audit",
    "",
    "Generated by `bun run scripts/license-audit.ts`.",
    `Root: ${result.rootDir}`,
    "",
    `Summary: ${result.summary.pass} pass, ${result.summary.fail} fail, ${result.summary.unknown} unknown, ${result.summary.total} total.`,
    "",
    "| Name | Version | License | Classification | Source | Package root | Path |",
    "|---|---:|---|---|---|---|---|",
  ];

  for (const pkg of result.packages) {
    lines.push([
      escapeCell(pkg.name),
      escapeCell(pkg.version),
      escapeCell(pkg.license),
      pkg.classification,
      escapeCell(pkg.source),
      escapeCell(pkg.packageRoot),
      escapeCell(pkg.path),
    ].join(" | ").replace(/^/, "| ").replace(/$/, " |"));
  }

  lines.push("", REPORT_FOOTER, "");
  return lines.join("\n");
}

async function isDirectory(path: string): Promise<boolean> {
  try {
    return (await stat(path)).isDirectory();
  } catch {
    return false;
  }
}

async function collectPackageRootsFromNodeModules(
  nodeModulesDir: string,
  seenRealRoots: Set<string>,
): Promise<string[]> {
  const roots: string[] = [];
  let entries;

  try {
    entries = await readdir(nodeModulesDir, { withFileTypes: true });
  } catch {
    return roots;
  }

  for (const entry of entries) {
    if (entry.name === ".bin" || entry.name.startsWith(".")) continue;

    const entryPath = join(nodeModulesDir, entry.name);
    if (entry.name.startsWith("@")) {
      if (!(await isDirectory(entryPath))) continue;
      const scopedEntries = await readdir(entryPath, { withFileTypes: true });
      for (const scopedEntry of scopedEntries) {
        if (scopedEntry.name.startsWith(".")) continue;
        const packageRoot = join(entryPath, scopedEntry.name);
        if (!(await isDirectory(packageRoot))) continue;
        const realRoot = await realpath(packageRoot);
        if (seenRealRoots.has(realRoot)) continue;
        seenRealRoots.add(realRoot);
        roots.push(packageRoot);
      }
      continue;
    }

    if (!(await isDirectory(entryPath))) continue;
    const realRoot = await realpath(entryPath);
    if (seenRealRoots.has(realRoot)) continue;
    seenRealRoots.add(realRoot);
    roots.push(entryPath);
  }

  return roots;
}

async function collectPackageRoots(rootDir: string): Promise<string[]> {
  const roots: string[] = [];
  const seenNodeModules = new Set<string>();
  const seenPackageRoots = new Set<string>();
  const queue = [join(rootDir, "node_modules")];

  while (queue.length > 0) {
    const nodeModulesDir = queue.shift()!;
    if (!(await isDirectory(nodeModulesDir))) continue;

    const realNodeModules = await realpath(nodeModulesDir);
    if (seenNodeModules.has(realNodeModules)) continue;
    seenNodeModules.add(realNodeModules);

    const packageRoots = await collectPackageRootsFromNodeModules(nodeModulesDir, seenPackageRoots);
    roots.push(...packageRoots);

    for (const packageRoot of packageRoots) {
      queue.push(join(packageRoot, "node_modules"));
    }
  }

  return roots;
}

async function readPackage(rootDir: string, packageRoot: string, warnings: string[]): Promise<LicensePackage | undefined> {
  const packageJsonPath = join(packageRoot, "package.json");
  let raw: string;

  try {
    raw = await readFile(packageJsonPath, "utf8");
  } catch {
    warnings.push(`missing package.json: ${displayPath(rootDir, packageJsonPath)}`);
    return undefined;
  }

  let pkg: Record<string, unknown>;
  try {
    pkg = JSON.parse(raw) as Record<string, unknown>;
  } catch (error) {
    warnings.push(`invalid package.json: ${displayPath(rootDir, packageJsonPath)} (${String(error)})`);
    return undefined;
  }

  const legacy = legacyLicensesText(pkg["licenses"]);
  const license = licenseText(pkg["license"]);
  const licenseInfo = license.license === "UNKNOWN" && legacy ? legacy : license;
  const name = typeof pkg["name"] === "string" && pkg["name"].trim() ? pkg["name"].trim() : displayPath(rootDir, packageRoot);
  const version = typeof pkg["version"] === "string" && pkg["version"].trim() ? pkg["version"].trim() : "UNKNOWN";
  const classification = classifyLicense(licenseInfo.license);

  return {
    name,
    version,
    license: licenseInfo.license,
    classification,
    source: licenseInfo.source,
    packageRoot: displayPath(rootDir, packageRoot),
    path: displayPath(rootDir, packageJsonPath),
  };
}

export async function auditLicenses(options: LicenseAuditOptions = {}): Promise<LicenseAuditResult> {
  const rootDir = await realpath(options.rootDir ?? process.cwd());
  const reportPath = options.reportPath ?? join(rootDir, "LICENSE-DEPS.md");
  const warnings: string[] = [];
  const packageRoots = await collectPackageRoots(rootDir);
  const packages = (await Promise.all(packageRoots.map((packageRoot) => readPackage(rootDir, packageRoot, warnings))))
    .filter((pkg): pkg is LicensePackage => pkg !== undefined)
    .sort((a, b) => `${a.name}@${a.version}:${a.path}`.localeCompare(`${b.name}@${b.version}:${b.path}`));

  for (const pkg of packages) {
    if (pkg.classification === "UNKNOWN") warnings.push(`unknown license: ${pkg.name}@${pkg.version} (${pkg.license})`);
  }

  const summary: LicenseAuditSummary = {
    total: packages.length,
    pass: packages.filter((pkg) => pkg.classification === "PASS").length,
    fail: packages.filter((pkg) => pkg.classification === "FAIL").length,
    unknown: packages.filter((pkg) => pkg.classification === "UNKNOWN").length,
  };

  const result: LicenseAuditResult = {
    ok: summary.fail === 0,
    generatedAt: new Date().toISOString(),
    rootDir,
    reportPath,
    summary,
    packages,
    warnings,
  };

  await mkdir(dirname(reportPath), { recursive: true });
  await writeFile(reportPath, renderReport(result));

  return result;
}

function readFlagValue(args: string[], flag: string): string | undefined {
  const index = args.indexOf(flag);
  if (index === -1) return undefined;
  return args[index + 1];
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  const result = await auditLicenses({
    rootDir: readFlagValue(args, "--root"),
    reportPath: readFlagValue(args, "--report"),
  });

  if (args.includes("--json")) {
    console.log(JSON.stringify(result, null, 2));
  } else {
    for (const warning of result.warnings) {
      console.warn(`warn: ${warning}`);
    }
    console.log(`license-audit: ${result.summary.pass} pass, ${result.summary.fail} fail, ${result.summary.unknown} unknown, ${result.summary.total} total`);
    console.log(`report: ${result.reportPath}`);
  }

  process.exit(result.ok ? 0 : 1);
}
