#!/usr/bin/env bash
# Re-capture web screenshots with real seeded data.
# No `set -e` — single timeouts must not abort the batch.

OUT="/Users/mkh/workspace/fulcrum/docs/manuals/screenshots/web"
BASE="http://localhost:5173"
PSLUG="manual-test-project"

mkdir -p "$OUT"

# Reset browser
playwright-cli close >/dev/null 2>&1
sleep 1
timeout 15 playwright-cli open --browser=msedge "${BASE}/" >/dev/null 2>&1
sleep 2
playwright-cli resize 1440 900 >/dev/null 2>&1
sleep 1

shot() {
  local file="$1"; local path="$2"; local wait="${3:-2}"
  echo ">>> $file <- $path"
  timeout 10 playwright-cli goto "${BASE}${path}" >/dev/null 2>&1
  sleep "$wait"
  timeout 10 playwright-cli screenshot --filename "${OUT}/${file}" >/dev/null 2>&1
}

# All 99 top-level routes
ROUTES=(
  "/:00-root"
  "/projects:01-projects"
  "/tasks:01-tasks-list"
  "/boards:02-boards"
  "/build-graph:03-build-graph"
  "/build-board:04-build-board"
  "/build-list:05-build-list"
  "/build-timeline:06-build-timeline"
  "/build-runs:07-build-runs"
  "/agent-dependency-board:08-agent-dependency-board"
  "/agents:09-agents"
  "/runs:10-runs"
  "/run-detail:11-run-detail"
  "/run-cancel:12-run-cancel"
  "/run-fork:13-run-fork"
  "/run-cost-tracking:14-run-cost-tracking"
  "/run-rate-limits:15-run-rate-limits"
  "/run-retry-policy:16-run-retry-policy"
  "/run-retry-prompt:17-run-retry-prompt"
  "/orchestration:18-orchestration"
  "/inbox:19-inbox"
  "/audit:20-audit"
  "/docs:21-docs"
  "/doc-labels:22-doc-labels"
  "/memory:23-memory"
  "/context:24-context"
  "/search:25-search"
  "/inference:26-inference"
  "/inference-models:27-inference-models"
  "/operate:28-operate"
  "/operate-alerts:29-operate-alerts"
  "/operate-mcp:30-operate-mcp"
  "/operate-plugins:31-operate-plugins"
  "/operate-telemetry:32-operate-telemetry"
  "/doctor:33-doctor"
  "/repos:34-repos"
  "/artifacts:35-artifacts"
  "/review:36-review"
  "/review-queue:37-review-queue"
  "/review-search:38-review-search"
  "/review-templates:39-review-templates"
  "/ship:40-ship"
  "/ship-archive:41-ship-archive"
  "/planning:42-planning"
  "/plan-prompts:43-plan-prompts"
  "/plan-prototypes:44-plan-prototypes"
  "/plan-review:45-plan-review"
  "/plan-session:46-plan-session"
  "/plan-templates:47-plan-templates"
  "/onboarding:48-onboarding"
  "/auth:49-auth"
  "/auth-flows:50-auth-flows"
  "/auth-2fa-verify:51-auth-2fa-verify"
  "/account-2fa-setup:52-account-2fa-setup"
  "/settings:53-settings"
  "/project-settings:54-project-settings"
  "/api-tokens:55-api-tokens"
  "/members:56-members"
  "/member-remove:57-member-remove"
  "/notifications-inbox:58-notifications-inbox"
  "/notifications-settings:59-notifications-settings"
  "/notifications-empty:60-notifications-empty"
  "/agent-cost-meter:61-agent-cost-meter"
  "/agent-keyboard-shortcuts:62-agent-keyboard-shortcuts"
  "/agent-notifications:63-agent-notifications"
  "/agent-session-export:64-agent-session-export"
  "/agent-session-fork:65-agent-session-fork"
  "/agent-session-timeline:66-agent-session-timeline"
  "/agent-token-chart:67-agent-token-chart"
  "/agent-tool-inspector:68-agent-tool-inspector"
  "/agent-window-controls:69-agent-window-controls"
  "/sessions-empty:70-sessions-empty"
  "/design-kit:71-design-kit"
  "/design-tokens:72-design-tokens"
  "/theme-picker:73-theme-picker"
  "/palette:74-palette"
  "/palette-cmd-k:75-palette-cmd-k"
  "/skill-detail:76-skill-detail"
  "/skill-registry:77-skill-registry"
  "/space-permissions:78-space-permissions"
  "/streamed-message:79-streamed-message"
  "/task-filters:80-task-filters"
  "/view-controls:81-view-controls"
  "/views-custom-fields:82-views-custom-fields"
  "/watch-list:83-watch-list"
  "/workspace:84-workspace"
  "/offline:85-offline"
  "/mobile-capture:86-mobile-capture"
  "/mobile-observability:87-mobile-observability"
  "/mobile-runs:88-mobile-runs"
  "/cross-cutting-mobile:89-cross-cutting-mobile"
  "/cross-cutting-motion:90-cross-cutting-motion"
  "/cross-cutting-offline:91-cross-cutting-offline"
  "/cross-cutting-perf:92-cross-cutting-perf"
  "/comments:93-comments"
  "/comments-block-thread:94-comments-block-thread"
  "/editor-blockquote:95-editor-blockquote"
  "/ai-assist:96-ai-assist"
)

for entry in "${ROUTES[@]}"; do
  path="${entry%:*}"
  name="${entry##*:}"
  shot "${name}.png" "$path"
done

# Project drill-down (uses real slug)
shot "70-proj-detail.png"    "/projects/${PSLUG}"
shot "71-proj-board.png"     "/projects/${PSLUG}/board"
shot "72-proj-backlog.png"   "/projects/${PSLUG}/backlog"
shot "73-proj-sprints.png"   "/projects/${PSLUG}/sprints"
shot "74-proj-modules.png"   "/projects/${PSLUG}/modules"
shot "75-proj-intake.png"    "/projects/${PSLUG}/intake"
shot "76-proj-calendar.png"  "/projects/${PSLUG}/calendar"
shot "77-proj-gantt.png"     "/projects/${PSLUG}/gantt"
shot "78-proj-repos.png"     "/projects/${PSLUG}/repos"
shot "79-proj-uat.png"       "/projects/${PSLUG}/uat"
shot "80-proj-review.png"    "/projects/${PSLUG}/review"
shot "81-proj-reports.png"   "/projects/${PSLUG}/reports"
shot "82-proj-routing.png"   "/projects/${PSLUG}/routing"
shot "83-proj-e2e.png"       "/projects/${PSLUG}/e2e"
shot "84-proj-updates.png"   "/projects/${PSLUG}/updates"
shot "85-proj-runs.png"      "/projects/${PSLUG}/runs"

echo "WEB DONE: $(ls $OUT | wc -l) files in $OUT"
