[package]
name = "fulcrum-daemon"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
fulcrum-config = { path = "../fulcrum-config" }
fulcrum-events = { path = "../fulcrum-events" }
fulcrum-kernel = { path = "../fulcrum-kernel" }
fulcrum-storage = { path = "../fulcrum-storage" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "fulcrum-daemon"
path = "src/main.rs"
