export type { ProductDb as LegacyDatabaseHandle } from "../../product-kernel/db/types.ts";
export { eventDispatcher } from "../../product-kernel/event-dispatcher.ts";
export {
  getFeatureBackend,
  isFeatureEnabled,
  loadFeatures,
  parseFeatures,
  type FeatureFlag,
} from "../../product-kernel/features.ts";
export { newUlid } from "../../product-kernel/ids.ts";
export {
  addTaskToSprint,
  appendEvent,
  closeSprint,
  createLocalOrg,
  createProject,
  createSprint,
  listBacklogTasks,
  listEventsFiltered,
  listReposForProject,
  listSavedViews as listRepositorySavedViews,
  listSprints,
  listSprintTasks,
  linkRepoToProject,
  removeTaskFromSprint,
  sprintCapacityUsed,
  updateSprint,
  type EventRow,
  type MetricsSnapshot,
  type RepoRow,
  type SprintRow,
  type TaskRow,
} from "../../product-kernel/store/repositories.ts";
export {
  getBlameForFile,
  getFileByPath,
  getFileContent,
  listIndexedBranches,
  listTreeChildren,
  type RepoFileBlameRow,
  type RepoFileContentRow,
  type RepoFileRow,
} from "../../product-kernel/store/repo-files.ts";
export {
  SETTINGS_SCREENS,
  addMember,
  createCustomFieldDef,
  createInvitation,
  createRoutingRule,
  createSavedView,
  deleteCustomFieldDef,
  deleteRoutingRule,
  deleteSavedView,
  listCustomFieldDefs,
  listFeatureFlags,
  listInvitations,
  listMembers,
  listRoutingRules,
  listSavedViews,
  reorderCustomFieldDefs,
  setFeatureFlag,
  settingsBreadcrumb,
  settingsScreenGroups,
  updateMemberRole,
  updateRoutingRule,
  updateSavedView,
  type CreateCustomFieldInput,
  type CreateRoutingRuleInput,
  type CreateSavedViewInput,
} from "../../product-kernel/store/settings.ts";
export {
  createConnectorRun,
  createCredential,
  deleteCredential,
  getTenantSetting,
  listConnectorRuns,
  listCredentials,
  listTenantSettings,
  upsertTenantSetting,
} from "../../product-kernel/store/settings-connectors-credentials.ts";
