export const GENERATED_DOMAIN_COMMANDS = [
  "agent_runs",
  "agents",
  "artifacts",
  "audit",
  "auth",
  "backup",
  "connectors",
  "context",
  "credentials",
  "customFieldDefs",
  "custom_fields",
  "db",
  "doc_comments",
  "doc_links",
  "doc_versions",
  "docs",
  "doctor",
  "errorLogs",
  "flags",
  "fulcrum_skills",
  "health",
  "inference",
  "invitations",
  "memories",
  "memory",
  "notifications",
  "notify",
  "orchestration",
  "orgs",
  "projects",
  "repo_branches",
  "repo_commits",
  "repos",
  "routing",
  "runs",
  "saved_views",
  "search",
  "sprints",
  "taskCustomFields",
  "tasks",
  "telemetry",
  "theme",
  "webhooks",
] as const;

export type GeneratedDomainCommand = (typeof GENERATED_DOMAIN_COMMANDS)[number];

export function isGeneratedDomainCommand(command: string): command is GeneratedDomainCommand {
  return (GENERATED_DOMAIN_COMMANDS as readonly string[]).includes(command);
}
